#!/usr/bin/env python3
"""Guard public Node runtime docs against stale support claims."""

from __future__ import annotations

import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]

SUPPORT_DOCS = (
    "docs/runtimes/nodejs/README.md",
    "docs/runtimes/nodejs/fundamentals.md",
    "docs/runtimes/nodejs/compatibility.md",
    "docs/runtimes/nodejs/configuration.md",
    "docs/runtimes/nodejs/reference/node-apis.md",
    "docs/runtimes/nodejs/reference/packages.md",
    "docs/architecture/runtime/node-compat-surface-matrix.md",
    "docs/architecture/runtime/deno-vs-nimbus-node-compat.md",
    "docs/architecture/runtime/node-lts-compat/node-lts-lanes.md",
)

FORBIDDEN_PATTERNS = (
    (
        re.compile(r"\b\d+(?:\.\d+)?%"),
        "hand-written percentage support claims belong in generated evidence",
    ),
    (
        re.compile(r"\b\d+\s+Node22 tests green\b", re.IGNORECASE),
        "hand-written Node22 pass-count prose makes the product default look like evidence priority",
    ),
    (
        re.compile(r"Official Node test files green", re.IGNORECASE),
        "hand-written official fixture totals belong in generated evidence",
    ),
    (
        re.compile(r"Node20:\s*supported selectable target", re.IGNORECASE),
        "Node20 is EOL legacy-grace coverage, not active supported LTS",
    ),
    (
        re.compile(r"\|\s*Node20\s*\|\s*Supported In Process\b", re.IGNORECASE),
        "Node20 table rows must not call the EOL lane production in-process support",
    ),
    (
        re.compile(r"Supported Node lanes\s*\|[^\n]*Node20", re.IGNORECASE),
        "Node20 must not be listed as a supported LTS lane",
    ),
    (
        re.compile(
            r"\|\s*Node26\s*\|[^\n]*\bPreview\b|Node26.{0,80}\bpreview\s+(?:target|lane)\b",
            re.IGNORECASE,
        ),
        "Node26 is Current/non-LTS, not a preview label",
    ),
    (
        re.compile(r"\bNimbus\s+(?:claims?|supports?|provides?)\s+(?:complete|full)\s+Node\b", re.IGNORECASE),
        "public docs must not overclaim complete Node support",
    ),
    (
        re.compile(r"Host-heavy behavior\s*\|\s*Supported In Process", re.IGNORECASE),
        "host-heavy behavior must remain service/microVM-routed",
    ),
    (
        re.compile(r"`node:(?:child_process|worker_threads|inspector|repl)`[^\n]*\|\s*Support\s*\|\s*Supported\b", re.IGNORECASE),
        "host-heavy Node builtins must not be documented as positive in-process package support",
    ),
)

REQUIRED_SNIPPETS = {
    "docs/runtimes/nodejs/README.md": (
        "Product default is a routing default, not an evidence priority.",
        "Node20 remains selectable only as legacy-grace regression coverage",
        "fundamentals.md",
        "reference/node-apis.md",
        "reference/packages.md",
    ),
    "docs/runtimes/nodejs/fundamentals.md": (
        "Product default is a routing default, not an evidence priority.",
        "Node26 is Current/non-LTS compatibility evidence",
        "Host-heavy behavior such as child processes",
        "diagnostic denials as boundaries, not as positive in-process support",
    ),
    "docs/runtimes/nodejs/compatibility.md": (
        "generated by scripts/runtime/node/publish_docs.py",
        "Node22 and Node24 are supported LTS targets with lane-local evidence.",
        "Node20 remains selectable as legacy-grace regression coverage",
        "Product default is a routing default, not an evidence priority.",
    ),
    "docs/runtimes/nodejs/configuration.md": (
        "product default from the lane registry",
        "evidence priority",
        "Node26 is a Current/non-LTS compatibility target, not a preview label",
    ),
    "docs/runtimes/nodejs/reference/node-apis.md": (
        "generated by scripts/runtime/node/publish_docs.py",
        "A diagnostic pass means Nimbus proved the denial or service/microVM route; it is not positive in-process support.",
        "Host-heavy behavior",
    ),
    "docs/runtimes/nodejs/reference/packages.md": (
        "generated by scripts/runtime/node/publish_docs.py",
        "`Diagnostic` rows prove an intentional denial or service route",
        "Native addons, package-owned binaries, child-process tools, and raw server listeners require service/microVM routing",
    ),
    "docs/architecture/runtime/node-compat-surface-matrix.md": (
        "Product default is a routing default, not an evidence priority.",
        "Node22 and Node24 are the current supported LTS lanes",
    ),
    "docs/architecture/runtime/deno-vs-nimbus-node-compat.md": (
        "it must not carry hand-maintained pass rates",
        "Product default is a routing default, not an evidence priority.",
    ),
}


def main() -> int:
    errors: list[str] = []
    for relative_path in SUPPORT_DOCS:
        path = REPO_ROOT / relative_path
        if not path.is_file():
            errors.append(f"missing public Node support doc: {relative_path}")
            continue
        text = path.read_text(encoding="utf-8")
        normalized_text = re.sub(r"\s+", " ", text)
        for pattern, reason in FORBIDDEN_PATTERNS:
            match = pattern.search(text)
            if match:
                errors.append(
                    f"{relative_path}: stale Node support prose `{match.group(0)}`: {reason}"
                )
        for snippet in REQUIRED_SNIPPETS.get(relative_path, ()):
            if snippet not in normalized_text:
                errors.append(
                    f"{relative_path}: missing required Node LTS support wording `{snippet}`"
                )

    if errors:
        for error in errors:
            print(f"error: {error}", file=sys.stderr)
        return 1

    print(
        "Node LTS docs guard passed: public docs avoid stale pass-rate, "
        "support-priority, and host-heavy overclaim prose"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
