[package]
name = "nimbus-services"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
publish.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
futures.workspace = true
nimbus-core = { path = "../nimbus-core" }
nimbus-node = { path = "../nimbus-node" }
nimbus-runtime = { path = "../nimbus-runtime" }
nimbus-sandbox = { path = "../nimbus-sandbox" }
nimbus-tenant = { path = "../nimbus-tenant" }
tokio.workspace = true
ulid.workspace = true
url.workspace = true

[dev-dependencies]
nimbus-egress = { path = "../nimbus-egress" }
tempfile.workspace = true
