pub const EGRESS_ENFORCEMENT_ENV: &str = "NIMBUS_SANDBOX_EGRESS_ENFORCEMENT_JSON";
pub const EGRESS_LEGACY_POLICY_ENV: &str = "NIMBUS_SANDBOX_EGRESS_POLICY_JSON";
pub const EGRESS_PROXY_URL_ENV: &str = "NIMBUS_SANDBOX_EGRESS_PROXY_URL";
pub const EGRESS_CA_BUNDLE_ENV: &str = "NIMBUS_SANDBOX_EGRESS_CA_BUNDLE";
pub const EGRESS_NODE_EXTRA_CA_CERTS_ENV: &str = "NODE_EXTRA_CA_CERTS";
pub const EGRESS_RESERVED_ENV_KEYS: [&str; 13] = [
    EGRESS_ENFORCEMENT_ENV,
    EGRESS_LEGACY_POLICY_ENV,
    EGRESS_PROXY_URL_ENV,
    EGRESS_CA_BUNDLE_ENV,
    EGRESS_NODE_EXTRA_CA_CERTS_ENV,
    "HTTP_PROXY",
    "http_proxy",
    "HTTPS_PROXY",
    "https_proxy",
    "ALL_PROXY",
    "all_proxy",
    "NO_PROXY",
    "no_proxy",
];
pub const EGRESS_ENFORCEMENT_SCHEMA_VERSION: u32 = 1;
