// Generated by @nimbus/codegen. Do not edit by hand.
// Inference audit — handlers whose return type came from a fallback or
// from a module/export-name convention rather than an informative validator
// or a readable query plan. Tighten the handler's `returns:` validator or
// register a query plan the codegen can read to drop the entry.
//   messages:list (convention-inferred)
//   messages:send (fallback-no-validator)
//   messages:summary (fallback-no-validator)
//   notifications:announce (fallback-no-validator)

import { makeMutationReference, makeQueryReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const api = {
  messages: {
    list: makeQueryReference<{
  "channel": string;
}, Doc<"messages">[]>("messages:list", "public"),
    send: makeMutationReference<{
  "channel": string;
  "author": string;
  "body": string;
}, unknown>("messages:send", "public"),
    summary: makeQueryReference<{
  "channel": string;
}, unknown>("messages:summary", "public")
  },
  notifications: {
    announce: makeMutationReference<{
  "channel": string;
  "email": string;
  "name": string;
  "body": string;
}, unknown>("notifications:announce", "public")
  },
  users: {
    getByEmail: makeQueryReference<{
  "email": string;
}, Doc<"users"> | null>("users:getByEmail", "public")
  }
};

export const internal = {
  users: {
    touch: makeMutationReference<{
  "email": string;
  "name": string;
}, Id<"users">>("users:touch", "internal")
  }
};
