// Generated by @nimbus/codegen. Do not edit by hand.
import type { GenericId } from "convex/values";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type TableNames = "messages" | "users";

export type Id<TableName extends string> = GenericId<TableName>;

type DocumentByTable = {
  "messages": {
    _id: Id<"messages">;
    _creationTime: number;
    _updateTime: number;
    "channel": string;
    "author": string;
    "body": string;
    "at": number;
  };
  "users": {
    _id: Id<"users">;
    _creationTime: number;
    _updateTime: number;
    "email": string;
    "name": string;
  };
};

type IndexNamesByTable = {
  "messages": "by_channel";
  "users": "by_email";
};

export type Doc<TableName extends TableNames> = DocumentByTable[TableName];

export type DataModel = {
  [TableName in TableNames]: {
    document: DocumentByTable[TableName];
    fieldPaths: keyof DocumentByTable[TableName];
    indexes: IndexNamesByTable[TableName];
  };
};
