// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel";

export const scheduledFunctions = {
  messages: {
    send: makeMutationReference<{
  "channel": string;
  "author": string;
  "body": string;
}, unknown>("messages:send", "public")
  },
  notifications: {
    announce: makeMutationReference<{
  "channel": string;
  "email": string;
  "name": string;
  "body": string;
}, unknown>("notifications:announce", "public")
  }
};

export const internalScheduledFunctions = {
  users: {
    touch: makeMutationReference<{
  "email": string;
  "name": string;
}, Id<"users">>("users:touch", "internal")
  }
};
