//! High-level envelope materials and crypto-shred state.
//!
//! This module is the subject-neutral API for callers. It keeps raw provider
//! calls, manifest validation, provider identity, keyring trace, and revocable
//! plaintext DEK handles in one place.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{SystemTime, UNIX_EPOCH};

use nimbus_core::{Error, Result};
use sha2::{Digest, Sha256};

use super::key::{DataEncryptionKey, WrappedDataKey};
use super::manifest::{KeyManifest, KeyManifestHeader, MANIFEST_VERSION, ManifestCipher};
use super::provider::{KeyProviderKind, LocalKeyProvider, LocalKeyProviderError};
use super::subject::LocalKeySubject;

/// The accepted envelope algorithm suite for persisted subject data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlgorithmSuite {
    /// Version-1 local envelope encryption with a random 256-bit DEK.
    LocalEnvelopeV1 { cipher: ManifestCipher },
}

impl AlgorithmSuite {
    pub fn from_manifest_cipher(cipher: ManifestCipher) -> Self {
        Self::LocalEnvelopeV1 { cipher }
    }

    pub fn manifest_cipher(self) -> ManifestCipher {
        match self {
            Self::LocalEnvelopeV1 { cipher } => cipher,
        }
    }
}

/// Template for data-encryption keys generated by the envelope keyring.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DekTemplate {
    pub suite: AlgorithmSuite,
    pub key_bytes: usize,
}

impl DekTemplate {
    pub fn for_manifest_cipher(cipher: ManifestCipher) -> Self {
        Self {
            suite: AlgorithmSuite::from_manifest_cipher(cipher),
            key_bytes: 32,
        }
    }
}

/// Non-secret commitment metadata for an envelope operation.
#[derive(Clone, PartialEq, Eq)]
pub struct CommitmentMetadata {
    pub manifest_aad_sha256: [u8; 32],
    pub wrapped_key_bytes: usize,
    pub subject_generation: u64,
}

impl CommitmentMetadata {
    fn new(header: &KeyManifestHeader, wrapped: &WrappedDataKey, subject_generation: u64) -> Self {
        let mut digest = Sha256::new();
        digest.update(header.to_aad());
        Self {
            manifest_aad_sha256: digest.finalize().into(),
            wrapped_key_bytes: wrapped.ciphertext.len(),
            subject_generation,
        }
    }
}

impl fmt::Debug for CommitmentMetadata {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CommitmentMetadata")
            .field("manifest_aad_sha256", &"[REDACTED_DIGEST]")
            .field("wrapped_key_bytes", &self.wrapped_key_bytes)
            .field("subject_generation", &self.subject_generation)
            .finish()
    }
}

/// Provider family used for stable audit and error mapping.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderFamily {
    MasterKeyFile,
    KeyDirectory,
    AwsKms,
}

/// Diagnostics-safe provider identity.
#[derive(Clone, PartialEq, Eq)]
pub struct ProviderIdentity {
    pub family: ProviderFamily,
    pub key_id_hint: Option<String>,
    pub region: Option<String>,
}

impl ProviderIdentity {
    pub fn from_kind(kind: &KeyProviderKind) -> Self {
        match kind {
            KeyProviderKind::MasterKeyFile { .. } => Self {
                family: ProviderFamily::MasterKeyFile,
                key_id_hint: None,
                region: None,
            },
            KeyProviderKind::KeyDirectory { .. } => Self {
                family: ProviderFamily::KeyDirectory,
                key_id_hint: None,
                region: None,
            },
            KeyProviderKind::AwsKms { key_id, region } => Self {
                family: ProviderFamily::AwsKms,
                key_id_hint: Some(redacted_key_hint(key_id)),
                region: region.clone(),
            },
        }
    }
}

impl fmt::Debug for ProviderIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("ProviderIdentity")
            .field("family", &self.family)
            .field("key_id_hint", &self.key_id_hint)
            .field("region", &self.region)
            .field("secret", &"[REDACTED]")
            .finish()
    }
}

fn redacted_key_hint(key_id: &str) -> String {
    let suffix: String = key_id
        .chars()
        .rev()
        .take(8)
        .collect::<String>()
        .chars()
        .rev()
        .collect();
    format!("...{suffix}")
}

/// Stable provider failure classes before errors cross crate boundaries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderFailureKind {
    WrongProvider,
    BadKey,
    DeniedDecrypt,
    InvalidCredentials,
    NetworkFailure,
    EndpointOrTls,
    Randomness,
    Io,
    Unknown,
}

impl ProviderFailureKind {
    pub fn classify(error: &LocalKeyProviderError) -> Self {
        match error {
            LocalKeyProviderError::UnsupportedCipher { .. } => Self::WrongProvider,
            LocalKeyProviderError::UnwrapError { .. }
            | LocalKeyProviderError::AwsKmsKeyNotFound { .. }
            | LocalKeyProviderError::KeyFileNotFound { .. }
            | LocalKeyProviderError::InvalidKeyFileSize { .. }
            | LocalKeyProviderError::InvalidMasterKeySize { .. } => Self::BadKey,
            LocalKeyProviderError::AwsKmsPermissionDenied { .. } => Self::DeniedDecrypt,
            LocalKeyProviderError::AwsKmsAuthError { .. }
            | LocalKeyProviderError::AwsKmsConfigurationError { .. } => Self::InvalidCredentials,
            LocalKeyProviderError::AwsKmsNetworkError { message, .. } => {
                if message.to_ascii_lowercase().contains("endpoint")
                    || message.to_ascii_lowercase().contains("tls")
                {
                    Self::EndpointOrTls
                } else {
                    Self::NetworkFailure
                }
            }
            LocalKeyProviderError::RandomError { .. } => Self::Randomness,
            LocalKeyProviderError::MasterKeyReadError { .. }
            | LocalKeyProviderError::KeyDirectoryReadError { .. } => Self::Io,
            LocalKeyProviderError::WrapError { .. }
            | LocalKeyProviderError::AwsKmsOperationError { .. } => Self::Unknown,
        }
    }
}

/// One redacted keyring trace event.
#[derive(Clone, PartialEq, Eq)]
pub struct KeyringTraceEvent {
    pub action: &'static str,
    pub provider: ProviderIdentity,
    pub subject_hash: [u8; 32],
    pub generation: u64,
    pub provider_failure: Option<ProviderFailureKind>,
}

impl fmt::Debug for KeyringTraceEvent {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("KeyringTraceEvent")
            .field("action", &self.action)
            .field("provider", &self.provider)
            .field("subject_hash", &"[REDACTED_DIGEST]")
            .field("generation", &self.generation)
            .field("provider_failure", &self.provider_failure)
            .finish()
    }
}

/// Redacted keyring trace for a materials operation.
#[derive(Clone, Default, PartialEq, Eq)]
pub struct KeyringTrace {
    events: Vec<KeyringTraceEvent>,
}

impl KeyringTrace {
    pub fn events(&self) -> &[KeyringTraceEvent] {
        &self.events
    }

    fn push(&mut self, event: KeyringTraceEvent) {
        self.events.push(event);
    }
}

impl fmt::Debug for KeyringTrace {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("KeyringTrace")
            .field("events", &self.events)
            .finish()
    }
}

/// Shared generation/tombstone state for revocable crypto material handles.
#[derive(Debug, Default)]
pub struct CryptoShredRegistry {
    subjects: Mutex<BTreeMap<String, SubjectShredState>>,
}

#[derive(Debug, Clone, Copy, Default)]
struct SubjectShredState {
    generation: u64,
    tombstoned: bool,
}

impl CryptoShredRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    fn acquire_generation(
        &self,
        subject: &LocalKeySubject,
    ) -> std::result::Result<u64, CryptoShredError> {
        let descriptor = subject.descriptor();
        let subjects = self
            .subjects
            .lock()
            .expect("crypto-shred registry lock should be available");
        let state = subjects.get(&descriptor).copied().unwrap_or_default();
        if state.tombstoned {
            Err(CryptoShredError::SubjectTombstoned { descriptor })
        } else {
            Ok(state.generation)
        }
    }

    fn assert_live(
        &self,
        descriptor: &str,
        handle_generation: u64,
    ) -> std::result::Result<(), CryptoShredError> {
        let subjects = self
            .subjects
            .lock()
            .expect("crypto-shred registry lock should be available");
        let state = subjects.get(descriptor).copied().unwrap_or_default();
        if state.tombstoned || state.generation != handle_generation {
            return Err(CryptoShredError::StaleHandle {
                descriptor: descriptor.to_string(),
                handle_generation,
                current_generation: state.generation,
            });
        }
        Ok(())
    }

    fn crypto_shred(&self, subject: &LocalKeySubject) -> u64 {
        let descriptor = subject.descriptor();
        let mut subjects = self
            .subjects
            .lock()
            .expect("crypto-shred registry lock should be available");
        let state = subjects.entry(descriptor).or_default();
        state.generation = state.generation.saturating_add(1);
        state.tombstoned = true;
        state.generation
    }
}

/// Errors produced when a revocable DEK handle is used after crypto-shred.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CryptoShredError {
    SubjectTombstoned {
        descriptor: String,
    },
    StaleHandle {
        descriptor: String,
        handle_generation: u64,
        current_generation: u64,
    },
}

impl fmt::Display for CryptoShredError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::SubjectTombstoned { descriptor } => {
                write!(f, "crypto-shred tombstone exists for {descriptor}")
            }
            Self::StaleHandle {
                descriptor,
                handle_generation,
                current_generation,
            } => write!(
                f,
                "stale crypto handle for {descriptor}: handle generation {handle_generation}, current generation {current_generation}"
            ),
        }
    }
}

impl std::error::Error for CryptoShredError {}

/// Revocable plaintext DEK handle.
pub struct RevocableDataKey {
    key: DataEncryptionKey,
    subject_descriptor: String,
    generation: u64,
    registry: Arc<CryptoShredRegistry>,
}

impl RevocableDataKey {
    fn new(
        key: DataEncryptionKey,
        subject: &LocalKeySubject,
        generation: u64,
        registry: Arc<CryptoShredRegistry>,
    ) -> Self {
        Self {
            key,
            subject_descriptor: subject.descriptor(),
            generation,
            registry,
        }
    }

    pub fn as_bytes(&self) -> std::result::Result<&[u8; 32], CryptoShredError> {
        self.registry
            .assert_live(&self.subject_descriptor, self.generation)?;
        Ok(self.key.as_bytes())
    }

    pub(crate) fn into_data_key(self) -> std::result::Result<DataEncryptionKey, CryptoShredError> {
        self.registry
            .assert_live(&self.subject_descriptor, self.generation)?;
        Ok(self.key)
    }
}

impl fmt::Debug for RevocableDataKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RevocableDataKey")
            .field("subject_descriptor", &"[REDACTED]")
            .field("generation", &self.generation)
            .field("plaintext", &"[REDACTED]")
            .finish()
    }
}

/// Complete crypto materials for opening or creating a protected subject.
pub struct CryptoMaterials {
    pub suite: AlgorithmSuite,
    pub template: DekTemplate,
    pub subject_descriptor: String,
    pub provider: ProviderIdentity,
    pub commitment: CommitmentMetadata,
    pub manifest: KeyManifest,
    pub trace: KeyringTrace,
    data_key: RevocableDataKey,
}

impl CryptoMaterials {
    pub fn revocable_data_key(&self) -> &RevocableDataKey {
        &self.data_key
    }

    #[cfg(test)]
    fn data_key_bytes(&self) -> std::result::Result<&[u8; 32], CryptoShredError> {
        self.data_key.as_bytes()
    }

    pub(crate) fn into_data_key(self) -> std::result::Result<DataEncryptionKey, CryptoShredError> {
        self.data_key.into_data_key()
    }
}

impl fmt::Debug for CryptoMaterials {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("CryptoMaterials")
            .field("suite", &self.suite)
            .field("template", &self.template)
            .field("subject_descriptor", &"[REDACTED]")
            .field("provider", &self.provider)
            .field("commitment", &self.commitment)
            .field("trace", &self.trace)
            .field("data_key", &"[REDACTED]")
            .finish()
    }
}

/// High-level envelope keyring over a concrete local provider.
pub struct EnvelopeKeyring<'a> {
    provider: &'a dyn LocalKeyProvider,
    shred_registry: Arc<CryptoShredRegistry>,
}

impl<'a> EnvelopeKeyring<'a> {
    pub fn new(provider: &'a dyn LocalKeyProvider) -> Self {
        Self {
            provider,
            shred_registry: Arc::new(CryptoShredRegistry::new()),
        }
    }

    pub fn with_shred_registry(
        provider: &'a dyn LocalKeyProvider,
        shred_registry: Arc<CryptoShredRegistry>,
    ) -> Self {
        Self {
            provider,
            shred_registry,
        }
    }

    pub fn shred_registry(&self) -> Arc<CryptoShredRegistry> {
        self.shred_registry.clone()
    }

    pub fn generate_materials(
        &self,
        subject: &LocalKeySubject,
        cipher: ManifestCipher,
    ) -> Result<CryptoMaterials> {
        let generation = self
            .shred_registry
            .acquire_generation(subject)
            .map_err(map_shred_error)?;
        let header = key_manifest_header(subject, self.provider.kind(), cipher);
        let provider_identity = ProviderIdentity::from_kind(&header.key_provider);
        let mut trace = KeyringTrace::default();
        let generated = match self.provider.generate_data_key(subject, &header) {
            Ok(generated) => generated,
            Err(error) => {
                trace.push(trace_event(
                    "generate",
                    provider_identity,
                    subject,
                    generation,
                    Some(ProviderFailureKind::classify(&error)),
                ));
                return Err(map_key_provider_error(error));
            }
        };
        let manifest = KeyManifest {
            header,
            wrapped_key: generated.wrapped().clone(),
        };
        let provider = ProviderIdentity::from_kind(&manifest.header.key_provider);
        trace.push(trace_event(
            "generate",
            provider.clone(),
            subject,
            generation,
            None,
        ));
        let commitment =
            CommitmentMetadata::new(&manifest.header, &manifest.wrapped_key, generation);
        Ok(CryptoMaterials {
            suite: AlgorithmSuite::from_manifest_cipher(cipher),
            template: DekTemplate::for_manifest_cipher(cipher),
            subject_descriptor: subject.descriptor(),
            provider,
            commitment,
            manifest,
            trace,
            data_key: RevocableDataKey::new(
                generated.into_plaintext(),
                subject,
                generation,
                self.shred_registry.clone(),
            ),
        })
    }

    pub fn open_materials(
        &self,
        manifest: &KeyManifest,
        subject: &LocalKeySubject,
        expected_cipher: ManifestCipher,
        protected_path: &Path,
    ) -> Result<CryptoMaterials> {
        validate_manifest(
            manifest,
            self.provider,
            subject,
            expected_cipher,
            protected_path,
        )?;
        let generation = self
            .shred_registry
            .acquire_generation(subject)
            .map_err(map_shred_error)?;
        let provider = ProviderIdentity::from_kind(&manifest.header.key_provider);
        let mut trace = KeyringTrace::default();
        let key =
            match self
                .provider
                .unwrap_data_key(subject, &manifest.wrapped_key, &manifest.header)
            {
                Ok(key) => key,
                Err(error) => {
                    trace.push(trace_event(
                        "unwrap",
                        provider,
                        subject,
                        generation,
                        Some(ProviderFailureKind::classify(&error)),
                    ));
                    return Err(map_key_provider_error(error));
                }
            };
        let provider = ProviderIdentity::from_kind(&manifest.header.key_provider);
        trace.push(trace_event(
            "unwrap",
            provider.clone(),
            subject,
            generation,
            None,
        ));
        let commitment =
            CommitmentMetadata::new(&manifest.header, &manifest.wrapped_key, generation);
        Ok(CryptoMaterials {
            suite: AlgorithmSuite::from_manifest_cipher(expected_cipher),
            template: DekTemplate::for_manifest_cipher(expected_cipher),
            subject_descriptor: subject.descriptor(),
            provider,
            commitment,
            manifest: manifest.clone(),
            trace,
            data_key: RevocableDataKey::new(key, subject, generation, self.shred_registry.clone()),
        })
    }
}

/// Result of destroying a wrapped DEK and tombstoning a subject.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CryptoShredOutcome {
    pub tombstone_path: PathBuf,
    pub destroyed_wrapped_dek: bool,
    pub generation: u64,
}

/// Delete the wrapped DEK sidecar and mark the subject as crypto-shredded.
///
/// This deliberately does not scrub ciphertext bytes. Destroying the wrapped
/// DEK plus revoking stale handles is the crypto-shred primitive.
pub fn crypto_shred_subject(
    protected_path: &Path,
    registry: &Arc<CryptoShredRegistry>,
    subject: &LocalKeySubject,
) -> Result<CryptoShredOutcome> {
    let manifest_path = KeyManifest::manifest_path(protected_path);
    let destroyed_wrapped_dek = match fs::remove_file(&manifest_path) {
        Ok(()) => true,
        Err(error) if error.kind() == io::ErrorKind::NotFound => false,
        Err(error) => {
            return Err(Error::Internal(format!(
                "failed to delete wrapped DEK manifest {} during crypto-shred: {error}",
                manifest_path.display()
            )));
        }
    };
    let generation = registry.crypto_shred(subject);
    let tombstone_path = shred_tombstone_path(protected_path);
    if let Some(parent) = tombstone_path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            Error::Internal(format!(
                "failed to create crypto-shred tombstone parent {}: {error}",
                parent.display()
            ))
        })?;
    }
    let tombstone = format!(
        "nimbus-crypto-shred-v1\nsubject={}\ngeneration={generation}\ndestroyed_wrapped_dek={destroyed_wrapped_dek}\n",
        subject.descriptor()
    );
    fs::write(&tombstone_path, tombstone).map_err(|error| {
        Error::Internal(format!(
            "failed to write crypto-shred tombstone {}: {error}",
            tombstone_path.display()
        ))
    })?;
    Ok(CryptoShredOutcome {
        tombstone_path,
        destroyed_wrapped_dek,
        generation,
    })
}

pub fn shred_tombstone_path(protected_path: &Path) -> PathBuf {
    let mut path = KeyManifest::manifest_path(protected_path)
        .as_os_str()
        .to_owned();
    path.push(".shredded");
    PathBuf::from(path)
}

pub(crate) fn validate_manifest(
    manifest: &KeyManifest,
    provider: &dyn LocalKeyProvider,
    subject: &LocalKeySubject,
    expected_cipher: ManifestCipher,
    protected_path: &Path,
) -> Result<()> {
    let expected_descriptor = subject.descriptor();
    if manifest.header.subject_descriptor != expected_descriptor {
        return Err(Error::InvalidInput(format!(
            "encryption manifest for {} belongs to '{}' instead of '{}'",
            protected_path.display(),
            manifest.header.subject_descriptor,
            expected_descriptor
        )));
    }
    if manifest.header.cipher != expected_cipher {
        return Err(Error::InvalidInput(format!(
            "encryption manifest for {} expects '{}' but '{}' was requested",
            protected_path.display(),
            manifest.header.cipher.as_str(),
            expected_cipher.as_str()
        )));
    }
    let expected_provider = provider.kind();
    if manifest.header.key_provider != expected_provider {
        return Err(Error::InvalidInput(format!(
            "encryption manifest for {} was wrapped by '{}' but current config uses '{}'",
            protected_path.display(),
            manifest.header.key_provider,
            expected_provider
        )));
    }
    Ok(())
}

pub(crate) fn map_key_provider_error(error: LocalKeyProviderError) -> Error {
    match error {
        LocalKeyProviderError::MasterKeyReadError { path, source } => {
            if source.kind() == io::ErrorKind::NotFound {
                Error::InvalidInput(format!("master key file not found: {}", path.display()))
            } else if source.kind() == io::ErrorKind::PermissionDenied {
                Error::PermissionDenied(format!(
                    "cannot read master key file (check permissions): {}",
                    path.display()
                ))
            } else {
                Error::Internal(format!(
                    "failed to read master key file {}: {source}",
                    path.display()
                ))
            }
        }
        LocalKeyProviderError::InvalidMasterKeySize { path, actual } => {
            Error::InvalidInput(format!(
                "master key file {} must contain exactly 32 bytes, found {actual}",
                path.display()
            ))
        }
        LocalKeyProviderError::KeyDirectoryReadError { path, source } => {
            if source.kind() == io::ErrorKind::PermissionDenied {
                Error::PermissionDenied(format!(
                    "cannot read key directory entry (check permissions): {}",
                    path.display()
                ))
            } else {
                Error::Internal(format!(
                    "failed to read key directory entry {}: {source}",
                    path.display()
                ))
            }
        }
        LocalKeyProviderError::KeyFileNotFound { path } => {
            Error::InvalidInput(format!("key file not found: {}", path.display()))
        }
        LocalKeyProviderError::InvalidKeyFileSize { path, actual } => Error::InvalidInput(format!(
            "key file {} must contain exactly 32 bytes, found {actual}",
            path.display()
        )),
        LocalKeyProviderError::AwsKmsKeyNotFound { key_id } => {
            Error::InvalidInput(format!("aws kms key not found: {key_id}"))
        }
        LocalKeyProviderError::AwsKmsConfigurationError { message } => {
            Error::InvalidInput(format!("aws kms configuration error: {message}"))
        }
        LocalKeyProviderError::AwsKmsAuthError { message }
        | LocalKeyProviderError::AwsKmsPermissionDenied { message, .. } => {
            Error::PermissionDenied(message)
        }
        LocalKeyProviderError::AwsKmsNetworkError { operation, message } => Error::Internal(
            format!("aws kms network error during {operation}: {message}"),
        ),
        LocalKeyProviderError::AwsKmsOperationError { operation, message } => {
            Error::Internal(format!("aws kms {operation} failed: {message}"))
        }
        LocalKeyProviderError::UnwrapError { message } => Error::PermissionDenied(message),
        LocalKeyProviderError::WrapError { message }
        | LocalKeyProviderError::UnsupportedCipher { cipher: message }
        | LocalKeyProviderError::RandomError { message } => Error::Internal(message),
    }
}

fn map_shred_error(error: CryptoShredError) -> Error {
    Error::PermissionDenied(error.to_string())
}

fn key_manifest_header(
    subject: &LocalKeySubject,
    key_provider: KeyProviderKind,
    cipher: ManifestCipher,
) -> KeyManifestHeader {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0);
    KeyManifestHeader {
        version: MANIFEST_VERSION,
        cipher,
        subject_descriptor: subject.descriptor(),
        key_provider,
        created_at: now,
        rotated_at: now,
    }
}

fn trace_event(
    action: &'static str,
    provider: ProviderIdentity,
    subject: &LocalKeySubject,
    generation: u64,
    provider_failure: Option<ProviderFailureKind>,
) -> KeyringTraceEvent {
    let mut digest = Sha256::new();
    digest.update(subject.descriptor().as_bytes());
    KeyringTraceEvent {
        action,
        provider,
        subject_hash: digest.finalize().into(),
        generation,
        provider_failure,
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use nimbus_core::{Error, TenantId};
    use tempfile::tempdir;

    use super::*;
    use crate::{MasterKeyFileProvider, WrappingCipher};

    fn write_test_key(path: &Path) {
        fs::write(path, [0x42u8; 32]).expect("test key should write");
    }

    fn test_subject() -> LocalKeySubject {
        LocalKeySubject::sqlite_tenant(
            TenantId::new("demo").expect("tenant id should build"),
            "demo.sqlite3",
        )
    }

    #[test]
    fn materials_round_trip_wrap_unwrap_parity() {
        let dir = tempdir().expect("tempdir should create");
        let key_path = dir.path().join("master.key");
        write_test_key(&key_path);
        let provider = MasterKeyFileProvider::new(key_path).expect("provider should create");
        let keyring = EnvelopeKeyring::new(&provider);
        let subject = test_subject();

        let materials = keyring
            .generate_materials(&subject, ManifestCipher::SqlCipher)
            .expect("materials should generate");
        let expected = *materials
            .data_key_bytes()
            .expect("generated key handle should be live");
        let opened = keyring
            .open_materials(
                &materials.manifest,
                &subject,
                ManifestCipher::SqlCipher,
                &dir.path().join("demo.sqlite3"),
            )
            .expect("materials should open");

        assert_eq!(
            opened
                .data_key_bytes()
                .expect("opened key handle should be live"),
            &expected
        );
        assert_eq!(
            opened.suite,
            AlgorithmSuite::from_manifest_cipher(ManifestCipher::SqlCipher)
        );
        assert_eq!(opened.template.key_bytes, 32);
        assert_eq!(opened.trace.events().len(), 1);
    }

    #[test]
    fn kek_rotation_rewrap_leaves_dek_intact() {
        let dir = tempdir().expect("tempdir should create");
        let key_path = dir.path().join("master.key");
        write_test_key(&key_path);
        let provider = MasterKeyFileProvider::new(key_path).expect("provider should create");
        let keyring = EnvelopeKeyring::new(&provider);
        let subject = test_subject();
        let materials = keyring
            .generate_materials(&subject, ManifestCipher::SqlCipher)
            .expect("materials should generate");
        let plaintext = *materials
            .data_key_bytes()
            .expect("generated key handle should be live");
        let mut rotated_header = materials.manifest.header.clone();
        rotated_header.rotated_at += 1;

        let rewrapped = provider
            .rewrap_data_key(&subject, &plaintext, &rotated_header)
            .expect("rewrap should succeed");
        let unwrapped = provider
            .unwrap_data_key(&subject, &rewrapped, &rotated_header)
            .expect("rewrapped key should unwrap");

        assert_eq!(unwrapped.as_bytes(), &plaintext);
    }

    #[test]
    fn provider_failure_mapping_covers_matrix() {
        let wrong_provider = LocalKeyProviderError::UnsupportedCipher {
            cipher: "wrong provider".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&wrong_provider),
            ProviderFailureKind::WrongProvider
        );

        let bad_key = LocalKeyProviderError::UnwrapError {
            message: "bad key".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&bad_key),
            ProviderFailureKind::BadKey
        );

        let denied = LocalKeyProviderError::AwsKmsPermissionDenied {
            operation: "denied decrypt",
            message: "denied decrypt".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&denied),
            ProviderFailureKind::DeniedDecrypt
        );

        let invalid_credentials = LocalKeyProviderError::AwsKmsAuthError {
            message: "invalid credentials".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&invalid_credentials),
            ProviderFailureKind::InvalidCredentials
        );

        let network_failure = LocalKeyProviderError::AwsKmsNetworkError {
            operation: "decrypt",
            message: "network failure".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&network_failure),
            ProviderFailureKind::NetworkFailure
        );

        let endpoint_tls = LocalKeyProviderError::AwsKmsNetworkError {
            operation: "decrypt",
            message: "endpoint TLS mismatch".to_string(),
        };
        assert_eq!(
            ProviderFailureKind::classify(&endpoint_tls),
            ProviderFailureKind::EndpointOrTls
        );
    }

    #[test]
    fn keyring_trace_debug_is_redacted() {
        let provider = ProviderIdentity::from_kind(&KeyProviderKind::MasterKeyFile {
            path: "/secret/master.key".to_string(),
        });
        let event = trace_event("unwrap", provider, &test_subject(), 7, None);
        let trace = KeyringTrace {
            events: vec![event],
        };
        let debug = format!("{trace:?}");

        assert!(debug.contains("REDACTED"));
        assert!(!debug.contains("master.key"));
        assert!(!debug.contains("demo.sqlite3"));
    }

    #[test]
    fn aad_tamper_fails_authentication_through_keyring() {
        let dir = tempdir().expect("tempdir should create");
        let key_path = dir.path().join("master.key");
        write_test_key(&key_path);
        let provider = MasterKeyFileProvider::new(key_path).expect("provider should create");
        let keyring = EnvelopeKeyring::new(&provider);
        let subject = test_subject();
        let materials = keyring
            .generate_materials(&subject, ManifestCipher::SqlCipher)
            .expect("materials should generate");
        let mut tampered = materials.manifest.clone();
        tampered.header.rotated_at += 1;

        let result = keyring.open_materials(
            &tampered,
            &subject,
            ManifestCipher::SqlCipher,
            &dir.path().join("demo.sqlite3"),
        );

        assert!(matches!(result, Err(Error::PermissionDenied(_))));
    }

    #[test]
    fn crypto_shred_deletes_wrapped_dek_and_revokes_pre_shred_handle() {
        let dir = tempdir().expect("tempdir should create");
        let key_path = dir.path().join("master.key");
        write_test_key(&key_path);
        let provider = MasterKeyFileProvider::new(key_path).expect("provider should create");
        let registry = Arc::new(CryptoShredRegistry::new());
        let keyring = EnvelopeKeyring::with_shred_registry(&provider, registry.clone());
        let subject = test_subject();
        let protected_path = dir.path().join("demo.sqlite3");
        fs::write(&protected_path, b"ciphertext").expect("protected bytes should write");
        let materials = keyring
            .generate_materials(&subject, ManifestCipher::SqlCipher)
            .expect("materials should generate");
        materials
            .manifest
            .write_for(&protected_path)
            .expect("manifest should write");
        let pre_shred_key = materials
            .data_key_bytes()
            .expect("pre-shred key should be live")
            .to_vec();

        let outcome = crypto_shred_subject(&protected_path, &registry, &subject)
            .expect("crypto-shred should complete");

        assert!(outcome.destroyed_wrapped_dek);
        assert!(outcome.tombstone_path.exists());
        assert!(!KeyManifest::manifest_path(&protected_path).exists());
        assert_eq!(
            materials
                .data_key_bytes()
                .expect_err("pre-shred handle should fail after shred"),
            CryptoShredError::StaleHandle {
                descriptor: subject.descriptor(),
                handle_generation: 0,
                current_generation: 1,
            }
        );
        assert_eq!(pre_shred_key.len(), 32);

        let reopen_result = keyring.open_materials(
            &materials.manifest,
            &subject,
            ManifestCipher::SqlCipher,
            &protected_path,
        );
        assert!(matches!(reopen_result, Err(Error::PermissionDenied(_))));
    }

    #[test]
    fn wrapped_data_key_debug_does_not_expose_plaintext() {
        let wrapped = WrappedDataKey::new(WrappingCipher::Aes256GcmSiv, vec![0xAB; 60]);
        let debug = format!("{wrapped:?}");

        assert!(debug.contains("Aes256GcmSiv"));
        assert!(!debug.contains("plaintext"));
    }
}
