const CORE_SEMANTICS_BATCH: &[NodeCompatBatchEntry] = &[
    shared_batch_case!(
        "test/parallel/test-assert-async.js",
        "node20/test/parallel/test-assert-async.js"
    ),
    split_batch_case!(
        "test/parallel/test-assert-calltracker-getCalls.js",
        "node20/test/parallel/test-assert-calltracker-getCalls.js",
        "node22/test/parallel/test-assert-calltracker-getCalls.js"
    ),
    shared_batch_case!(
        "test/parallel/test-assert-calltracker-report.js",
        "node20/test/parallel/test-assert-calltracker-report.js"
    ),
    shared_batch_case!(
        "test/parallel/test-assert-calltracker-verify.js",
        "node20/test/parallel/test-assert-calltracker-verify.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-assert-checktag.js",
        "node22/test/parallel/test-assert-checktag.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-assert-class-destructuring.js",
        "test/parallel/test-assert-class-destructuring.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-assert-deep-with-error.js",
        "test/parallel/test-assert-deep-with-error.js"
    ),
    shared_batch_case!(
        "test/parallel/test-assert-fail-deprecation.js",
        "node20/test/parallel/test-assert-fail-deprecation.js"
    ),
    shared_batch_case!(
        "test/parallel/test-assert-fail.js",
        "node20/test/parallel/test-assert-fail.js"
    ),
    shared_batch_case_with_extra!(
        "test/parallel/test-assert-first-line.js",
        "node20/test/parallel/test-assert-first-line.js",
        NODE20_ASSERT_FIRST_LINE_EXTRA_FILES
    ),
    shared_batch_case!(
        "test/parallel/test-assert-if-error.js",
        "node20/test/parallel/test-assert-if-error.js"
    ),
    split_batch_case!(
        "test/parallel/test-assert-typedarray-deepequal.js",
        "node20/test/parallel/test-assert-typedarray-deepequal.js",
        "node22/test/parallel/test-assert-typedarray-deepequal.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-alloc.js",
        "node20/test/parallel/test-buffer-alloc.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-arraybuffer.js",
        "node20/test/parallel/test-buffer-arraybuffer.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-ascii.js",
        "node20/test/parallel/test-buffer-ascii.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-badhex.js",
        "node20/test/parallel/test-buffer-badhex.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-bigint64.js",
        "node20/test/parallel/test-buffer-bigint64.js",
        "node22/test/parallel/test-buffer-bigint64.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-bytelength.js",
        "node20/test/parallel/test-buffer-bytelength.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-compare.js",
        "node20/test/parallel/test-buffer-compare.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-compare-offset.js",
        "node20/test/parallel/test-buffer-compare-offset.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-copy.js",
        "node20/test/parallel/test-buffer-copy.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-concat.js",
        "node20/test/parallel/test-buffer-concat.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-constants.js",
        "node20/test/parallel/test-buffer-constants.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-constructor-deprecation-error.js",
        "node20/test/parallel/test-buffer-constructor-deprecation-error.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-equals.js",
        "node20/test/parallel/test-buffer-equals.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-failed-alloc-typed-arrays.js",
        "node20/test/parallel/test-buffer-failed-alloc-typed-arrays.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-fill.js",
        "node20/test/parallel/test-buffer-fill.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-fakes.js",
        "node20/test/parallel/test-buffer-fakes.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-from.js",
        "node20/test/parallel/test-buffer-from.js",
        "test/parallel/test-buffer-from.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-indexof.js",
        "node20/test/parallel/test-buffer-indexof.js",
        "test/parallel/test-buffer-indexof.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-inspect.js",
        "node20/test/parallel/test-buffer-inspect.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-includes.js",
        "node20/test/parallel/test-buffer-includes.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-inheritance.js",
        "node20/test/parallel/test-buffer-inheritance.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-isencoding.js",
        "node20/test/parallel/test-buffer-isencoding.js",
        "test/parallel/test-buffer-isencoding.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-iterator.js",
        "node20/test/parallel/test-buffer-iterator.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-new.js",
        "node20/test/parallel/test-buffer-new.js",
        "node22/test/parallel/test-buffer-new.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-no-negative-allocation.js",
        "node20/test/parallel/test-buffer-no-negative-allocation.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-nopendingdep-map.js",
        "node20/test/parallel/test-buffer-nopendingdep-map.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-of-no-deprecation.js",
        "node20/test/parallel/test-buffer-of-no-deprecation.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-over-max-length.js",
        "node20/test/parallel/test-buffer-over-max-length.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-parent-property.js",
        "node20/test/parallel/test-buffer-parent-property.js",
        "node22/test/parallel/test-buffer-parent-property.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-pending-deprecation.js",
        "node20/test/parallel/test-buffer-pending-deprecation.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-prototype-inspect.js",
        "node20/test/parallel/test-buffer-prototype-inspect.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-safe-unsafe.js",
        "node20/test/parallel/test-buffer-safe-unsafe.js",
        "node22/test/parallel/test-buffer-safe-unsafe.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-read.js",
        "node20/test/parallel/test-buffer-read.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-readdouble.js",
        "node20/test/parallel/test-buffer-readdouble.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-readfloat.js",
        "node20/test/parallel/test-buffer-readfloat.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-readint.js",
        "node20/test/parallel/test-buffer-readint.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-readuint.js",
        "node20/test/parallel/test-buffer-readuint.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-buffer-resizable.js",
        "node22/test/parallel/test-buffer-resizable.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-sharedarraybuffer.js",
        "node20/test/parallel/test-buffer-sharedarraybuffer.js",
        "node22/test/parallel/test-buffer-sharedarraybuffer.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-set-inspect-max-bytes.js",
        "node20/test/parallel/test-buffer-set-inspect-max-bytes.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-buffer-slow.js",
        "node22/test/parallel/test-buffer-slow.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-slice.js",
        "node20/test/parallel/test-buffer-slice.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-swap.js",
        "node20/test/parallel/test-buffer-swap.js",
        "node22/test/parallel/test-buffer-swap.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-tojson.js",
        "node20/test/parallel/test-buffer-tojson.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-tostring.js",
        "node20/test/parallel/test-buffer-tostring.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-tostring-range.js",
        "node20/test/parallel/test-buffer-tostring-range.js",
        "node22/test/parallel/test-buffer-tostring-range.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-tostring-rangeerror.js",
        "node20/test/parallel/test-buffer-tostring-rangeerror.js",
        "node22/test/parallel/test-buffer-tostring-rangeerror.js"
    ),
    split_batch_case!(
        "test/parallel/test-buffer-write.js",
        "node20/test/parallel/test-buffer-write.js",
        "test/parallel/test-buffer-write.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-writedouble.js",
        "node20/test/parallel/test-buffer-writedouble.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-writefloat.js",
        "node20/test/parallel/test-buffer-writefloat.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-writeint.js",
        "node20/test/parallel/test-buffer-writeint.js"
    ),
    shared_batch_case!(
        "test/parallel/test-buffer-writeuint.js",
        "node20/test/parallel/test-buffer-writeuint.js"
    ),
    split_batch_case!(
        "test/parallel/test-console-assign-undefined.js",
        "node20/test/parallel/test-console-assign-undefined.js",
        "test/parallel/test-console-assign-undefined.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-async-write-error.js",
        "node20/test/parallel/test-console-async-write-error.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-console-clear.js",
        "test/parallel/test-console-clear.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-count.js",
        "node20/test/parallel/test-console-count.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-log-stdio-broken-dest.js",
        "node20/test/parallel/test-console-log-stdio-broken-dest.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-table.js",
        "node20/test/parallel/test-console-table.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-tty-colors.js",
        "node20/test/parallel/test-console-tty-colors.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-log-throw-primitive.js",
        "node20/test/parallel/test-console-log-throw-primitive.js"
    ),
    split_batch_case!(
        "test/parallel/test-console-formatTime.js",
        "node20/test/parallel/test-console-formatTime.js",
        "node22/test/parallel/test-console-formatTime.js"
    ),
    shared_batch_case_with_extra!(
        "test/parallel/test-console-group.js",
        "node20/test/parallel/test-console-group.js",
        NODE20_CONSOLE_GROUP_EXTRA_FILES
    ),
    split_batch_case!(
        "test/parallel/test-console-instance.js",
        "node20/test/parallel/test-console-instance.js",
        "test/parallel/test-console-instance.js"
    ),
    split_batch_case!(
        "test/parallel/test-console-methods.js",
        "node20/test/parallel/test-console-methods.js",
        "test/parallel/test-console-methods.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-not-call-toString.js",
        "node20/test/parallel/test-console-not-call-toString.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-no-swallow-stack-overflow.js",
        "node20/test/parallel/test-console-no-swallow-stack-overflow.js"
    ),
    split_batch_case!(
        "test/parallel/test-console-self-assign.js",
        "node20/test/parallel/test-console-self-assign.js",
        "test/parallel/test-console-self-assign.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-stdio-setters.js",
        "node20/test/parallel/test-console-stdio-setters.js"
    ),
    shared_batch_case!(
        "test/parallel/test-console-sync-write-error.js",
        "node20/test/parallel/test-console-sync-write-error.js"
    ),
    split_batch_case!(
        "test/parallel/test-events-getmaxlisteners.js",
        "node20/test/parallel/test-events-getmaxlisteners.js",
        "test/parallel/test-events-getmaxlisteners.js"
    ),
    split_batch_case!(
        "test/parallel/test-events-list.js",
        "node20/test/parallel/test-events-list.js",
        "test/parallel/test-events-list.js"
    ),
    shared_batch_case!(
        "test/parallel/test-events-listener-count-with-listener.js",
        "node20/test/parallel/test-events-listener-count-with-listener.js"
    ),
    shared_batch_case_with_extra!(
        "test/parallel/test-events-add-abort-listener.mjs",
        "node20/test/parallel/test-events-add-abort-listener.mjs",
        NODE20_COMMON_INDEX_MJS_EXTRA_FILES
    ),
    node22_only_batch_case!(
        "test/parallel/test-events-once.js",
        "node22/test/parallel/test-events-once.js"
    ),
    shared_batch_case!(
        "test/parallel/test-events-static-geteventlisteners.js",
        "node20/test/parallel/test-events-static-geteventlisteners.js"
    ),
    split_batch_case!(
        "test/parallel/test-path-basename.js",
        "node20/test/parallel/test-path-basename.js",
        "test/parallel/test-path-basename.js"
    ),
    split_batch_case!(
        "test/parallel/test-path-dirname.js",
        "node20/test/parallel/test-path-dirname.js",
        "test/parallel/test-path-dirname.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-extname.js",
        "node20/test/parallel/test-path-extname.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-glob.js",
        "node20/test/parallel/test-path-glob.js"
    ),
    split_batch_case!(
        "test/parallel/test-path-isabsolute.js",
        "node20/test/parallel/test-path-isabsolute.js",
        "test/parallel/test-path-isabsolute.js"
    ),
    split_batch_case!(
        "test/parallel/test-path-join.js",
        "node20/test/parallel/test-path-join.js",
        "test/parallel/test-path-join.js"
    ),
    node20_only_batch_case!(
        "test/parallel/test-path-normalize.js",
        "node20/test/parallel/test-path-normalize.js"
    ),
    node20_only_batch_case!(
        "test/parallel/test-path-makelong.js",
        "node20/test/parallel/test-path-makelong.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-parse-format.js",
        "node20/test/parallel/test-path-parse-format.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-posix-exists.js",
        "node20/test/parallel/test-path-posix-exists.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-posix-relative-on-windows.js",
        "node20/test/parallel/test-path-posix-relative-on-windows.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-relative.js",
        "node20/test/parallel/test-path-relative.js"
    ),
    shared_batch_case!(
        "test/parallel/test-path-win32-exists.js",
        "node20/test/parallel/test-path-win32-exists.js"
    ),
    split_batch_case!(
        "test/parallel/test-path-zero-length-strings.js",
        "node20/test/parallel/test-path-zero-length-strings.js",
        "test/parallel/test-path-zero-length-strings.js"
    ),
    split_batch_case!(
        "test/parallel/test-path.js",
        "node20/test/parallel/test-path.js",
        "test/parallel/test-path.js"
    ),
    split_batch_case!(
        "test/parallel/test-punycode.js",
        "node20/test/parallel/test-punycode.js",
        "test/parallel/test-punycode.js"
    ),
    split_batch_case!(
        "test/parallel/test-querystring-escape.js",
        "node20/test/parallel/test-querystring-escape.js",
        "test/parallel/test-querystring-escape.js"
    ),
    split_batch_case!(
        "test/parallel/test-querystring-maxKeys-non-finite.js",
        "node20/test/parallel/test-querystring-maxKeys-non-finite.js",
        "test/parallel/test-querystring-maxKeys-non-finite.js"
    ),
    shared_batch_case!(
        "test/parallel/test-querystring-multichar-separator.js",
        "node20/test/parallel/test-querystring-multichar-separator.js"
    ),
    shared_batch_case!(
        "test/parallel/test-querystring.js",
        "node20/test/parallel/test-querystring.js"
    ),
    split_batch_case!(
        "test/parallel/test-string-decoder-end.js",
        "node20/test/parallel/test-string-decoder-end.js",
        "test/parallel/test-string-decoder-end.js"
    ),
    shared_batch_case!(
        "test/parallel/test-string-decoder-fuzz.js",
        "node20/test/parallel/test-string-decoder-fuzz.js"
    ),
    shared_batch_case!(
        "test/parallel/test-string-decoder.js",
        "node20/test/parallel/test-string-decoder.js"
    ),
    shared_batch_case!(
        "test/parallel/test-url-domain-ascii-unicode.js",
        "node20/test/parallel/test-url-domain-ascii-unicode.js"
    ),
    shared_batch_case!(
        "test/parallel/test-url-fileurltopath.js",
        "node20/test/parallel/test-url-fileurltopath.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-format.js",
        "node20/test/parallel/test-url-format.js",
        "test/parallel/test-url-format.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-format-invalid-input.js",
        "node20/test/parallel/test-url-format-invalid-input.js",
        "test/parallel/test-url-format-invalid-input.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-format-whatwg.js",
        "node20/test/parallel/test-url-format-whatwg.js",
        "test/parallel/test-url-format-whatwg.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-url-invalid-file-url-path-input.js",
        "test/parallel/test-url-invalid-file-url-path-input.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-parse-format.js",
        "node20/test/parallel/test-url-parse-format.js",
        "node22/test/parallel/test-url-parse-format.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-parse-invalid-input.js",
        "node20/test/parallel/test-url-parse-invalid-input.js",
        "node22/test/parallel/test-url-parse-invalid-input.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-parse-query.js",
        "node20/test/parallel/test-url-parse-query.js",
        "test/parallel/test-url-parse-query.js"
    ),
    shared_batch_case!(
        "test/parallel/test-url-pathtofileurl.js",
        "node20/test/parallel/test-url-pathtofileurl.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-relative.js",
        "node20/test/parallel/test-url-relative.js",
        "test/parallel/test-url-relative.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-revokeobjecturl.js",
        "node20/test/parallel/test-url-revokeobjecturl.js",
        "test/parallel/test-url-revokeobjecturl.js"
    ),
    split_batch_case!(
        "test/parallel/test-url-urltooptions.js",
        "node20/test/parallel/test-url-urltooptions.js",
        "test/parallel/test-url-urltooptions.js"
    ),
];

