const NETWORKING_BATCH: &[NodeCompatBatchEntry] = &[
    shared_official_batch_case!("test/parallel/test-dns-get-server.js"),
    shared_official_batch_case!("test/parallel/test-dns-set-default-order.js"),
    shared_official_batch_case!("test/parallel/test-dns-default-order-ipv4.js"),
    shared_official_batch_case!("test/parallel/test-dns-default-order-ipv6.js"),
    shared_official_batch_case!("test/parallel/test-dns-default-order-verbatim.js"),
    shared_official_batch_case!("test/parallel/test-stream-finished.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-stream-pipeline.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-stream-pipeline.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-stream-pipeline.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-net-connect-options-invalid.js"),
    shared_official_batch_case!("test/parallel/test-net-isip.js"),
    shared_official_batch_case!("test/parallel/test-net-isipv4.js"),
    shared_official_batch_case!("test/parallel/test-net-isipv6.js"),
    shared_official_batch_case!("test/parallel/test-net-connect-no-arg.js"),
    shared_official_batch_case!("test/parallel/test-net-listening.js"),
    shared_official_batch_case!("test/parallel/test-net-listen-close-server.js"),
    shared_official_batch_case!("test/parallel/test-net-server-close.js"),
    shared_official_batch_case!("test/parallel/test-net-server-call-listen-multiple-times.js"),
    shared_official_batch_case!("test/parallel/test-net-server-listen-options.js"),
    shared_official_batch_case!("test/parallel/test-net-server-listen-options-signal.js"),
    shared_official_batch_case!("test/parallel/test-net-server-unref-persistent.js"),
    shared_official_batch_case!("test/parallel/test-net-after-close.js"),
    shared_official_batch_case!("test/parallel/test-net-settimeout.js"),
    shared_official_batch_case!("test/parallel/test-net-can-reset-timeout.js"),
    shared_official_batch_case!("test/parallel/test-net-socket-close-after-end.js"),
    shared_official_batch_case!("test/parallel/test-net-socket-connecting.js"),
    shared_official_batch_case!("test/parallel/test-net-local-address-port.js"),
    shared_official_batch_case!("test/parallel/test-http-client-defaults.js"),
    shared_official_batch_case!("test/parallel/test-http-client-get-url.js"),
    shared_official_batch_case!("test/parallel/test-http-client-request-options.js"),
    shared_official_batch_case!("test/parallel/test-http-client-upload.js"),
    shared_official_batch_case!("test/parallel/test-http-client-upload-buf.js"),
    shared_official_batch_case!("test/parallel/test-http-automatic-headers.js"),
    shared_official_batch_case!("test/parallel/test-http-client-close-event.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-getname.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-close.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-timeout-option.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-keepalive.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-keepalive-delay.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-agent-maxsockets.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-agent-maxsockets-respected.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-agent-maxtotalsockets.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http-agent-scheduling.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-timeout.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-false.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-no-protocol.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-null.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-remove.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-agent-destroyed-socket.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http-agent-error-on-idle.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-uninitialized.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-uninitialized-with-handle.js"),
    shared_official_batch_case!("test/parallel/test-http-agent-abort-controller.js"),
    shared_official_batch_case!("test/parallel/test-http-client-timeout-option.js"),
    shared_official_batch_case!("test/parallel/test-http-client-set-timeout.js"),
    shared_official_batch_case!("test/parallel/test-http-client-response-timeout.js"),
    shared_official_batch_case!("test/parallel/test-http-set-timeout.js"),
    shared_official_batch_case!("test/parallel/test-http-contentLength0.js"),
    shared_official_batch_case!("test/parallel/test-http-head-request.js"),
    shared_official_batch_case!("test/parallel/test-http-server-options-incoming-message.js"),
    shared_official_batch_case!("test/parallel/test-http-server-options-server-response.js"),
    shared_official_batch_case!("test/parallel/test-http-response-add-header-after-sent.js"),
    shared_official_batch_case!("test/parallel/test-http-response-remove-header-after-sent.js"),
    shared_official_batch_case!("test/parallel/test-http-response-no-headers.js"),
    shared_official_batch_case!("test/parallel/test-http-response-readable.js"),
    shared_official_batch_case!("test/parallel/test-http-response-setheaders.js"),
    shared_official_batch_case!("test/parallel/test-http-response-close.js"),
    shared_official_batch_case!("test/parallel/test-http-response-cork.js"),
    shared_official_batch_case!("test/parallel/test-http-response-multi-content-length.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-status-code.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-response-multiheaders.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http-head-response-has-no-body.js"),
    shared_official_batch_case!("test/parallel/test-http-head-response-has-no-body-end.js"),
    shared_official_batch_case!(
        "test/parallel/test-http-head-response-has-no-body-end-implicit-headers.js"
    ),
    shared_official_batch_case!("test/parallel/test-http-head-throw-on-response-body-write.js"),
    shared_official_batch_case!("test/parallel/test-http-status-message.js"),
    shared_official_batch_case!("test/parallel/test-http-write-head-2.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-status-reason-invalid-chars.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-response-statuscode.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-response-status-message.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http-write-head.js"),
    shared_official_batch_case!("test/parallel/test-http-response-writehead-returns-this.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http-response-splitting.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-http-write-head-after-set-header.js",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some(
            "node22/test/parallel/test-http-write-head-after-set-header.js",
        ),
        node24_fixture_source_path: Some(
            "node24/test/parallel/test-http-write-head-after-set-header.js",
        ),
        shared_extra_files: COMMON_COUNTDOWN_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-net-end-without-connect.js"),
    shared_official_batch_case!("test/parallel/test-http2-util-asserts.js"),
    shared_official_batch_case!("test/parallel/test-http2-util-assert-valid-pseudoheader.js"),
    shared_official_batch_case!("test/parallel/test-http2-util-nghttp2error.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-agent-constructor.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-agent-getname.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-agent.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-agent-abort-controller.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-options-incoming-message.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-options-server-response.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-client-get-url.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http2-getpackedsettings.js"),
    shared_official_batch_case!("test/parallel/test-http2-util-headers-list.js"),
    shared_official_batch_case!("test/parallel/test-http2-util-update-options-buffer.js"),
    shared_official_batch_case!("test/parallel/test-http2-misc-util.js"),
    shared_official_batch_case!("test/parallel/test-http2-status-code.js"),
    shared_official_batch_case!("test/parallel/test-http2-status-code-invalid.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http2-multi-content-length.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http2-response-splitting.js"),
    shared_official_batch_case!("test/parallel/test-http2-options-server-request.js"),
    shared_official_batch_case!("test/parallel/test-http2-options-server-response.js"),
    shared_official_batch_case!("test/parallel/test-http2-zero-length-header.js"),
    shared_official_batch_case!("test/parallel/test-http2-multiheaders.js"),
    shared_official_batch_case!("test/parallel/test-http2-multiheaders-raw.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-end.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-write.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-writehead.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-writehead-array.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-statuscode.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-statusmessage.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-statusmessage-property.js"
    ),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-statusmessage-property-set.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-headers.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-end.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-headers.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-host.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-pause.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http2-compat-serverrequest-pipe.js",
        COMMON_HTTP2_COMPAT_SERVERREQUEST_PIPE_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-settimeout.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverrequest-trailers.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-close.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http2-compat-serverresponse-destroy.js",
        COMMON_COUNTDOWN_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-drain.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-end-after-statuses-without-body.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-finished.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-flushheaders.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-headers-after-destroy.js"
    ),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-headers-send-date.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-settimeout.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-serverresponse-trailers.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-write-early-hints.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-write-early-hints-invalid-argument-type.js"
    ),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-write-early-hints-invalid-argument-value.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-write-head-destroyed.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-aborted.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-http2-compat-client-upload-reject.js",
        COMMON_HTTP2_COMPAT_SERVERREQUEST_PIPE_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-errors.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-expect-continue-check.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-expect-continue.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-expect-handling.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-method-connect.js"),
    shared_official_batch_case!(
        "test/parallel/test-http2-compat-serverresponse-createpushresponse.js"
    ),
    shared_official_batch_case!("test/parallel/test-http2-compat-short-stream-client-server.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-socket-destroy-delayed.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-socket-set.js"),
    shared_official_batch_case!("test/parallel/test-http2-compat-socket.js"),
    shared_node20_node22_with_node24_override_case_with_extra!(
        "test/parallel/test-https-agent-create-connection.js",
        "node24/test/parallel/test-https-agent-create-connection.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_batch_case_with_extra!(
        "test/parallel/test-https-agent-disable-session-reuse.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_with_node24_override_case_with_extra!(
        "test/parallel/test-https-agent-servername.js",
        "node24/test/parallel/test-https-agent-servername.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_batch_case_with_extra!(
        "test/parallel/test-https-agent-session-injection.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_with_node24_override_case_with_extra!(
        "test/parallel/test-https-agent-sni.js",
        "node24/test/parallel/test-https-agent-sni.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_batch_case_with_extra!(
        "test/parallel/test-https-agent-sockets-leak.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_node20_node22_batch_case_with_extra!(
        "test/parallel/test-https-client-override-global-agent.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-abortcontroller.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-argument-of-creating.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-byteswritten.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-close.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-max-headers-count.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-request-arguments.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-headers-timeout.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-request-timeout.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-set-timeout-server.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-simple.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-timeout.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-timeout-server.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-timeout-server-2.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-close-all.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-close-destroy-timeout.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-close-idle.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-socket-options.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-keep-alive-drop-requests.js",
        COMMON_TLS_KEY_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-connections-checking-leak.js",
        COMMON_TLS_KEY_COUNTDOWN_GC_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-client-checkServerIdentity.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-client-reject.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-connecting-to-http.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-drain.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-eof-for-eom.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-host-headers.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-insecure-parse-per-stream.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-max-header-size-per-stream.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-options-boolean-check.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-server-async-dispose.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-truncate.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-selfsigned-no-keycertsign-no-crash.js",
        COMMON_TLS_SESSION_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-client-resume.js",
        COMMON_TLS_SESSION_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-resume-after-renew.js",
        COMMON_TLS_SESSION_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-pfx.js",
        COMMON_TLS_SESSION_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-unix-socket-self-signed.js",
        COMMON_TLS_SESSION_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-https-strict.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-https-agent-session-reuse.js",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some("node22/test/parallel/test-https-agent-session-reuse.js"),
        node24_fixture_source_path: None,
        shared_extra_files: COMMON_TLS_KEY_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-https-agent-keylog.js",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some("node22/test/parallel/test-https-agent-keylog.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-https-agent-keylog.js"),
        shared_extra_files: COMMON_TLS_KEY_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-https-hwm.js",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some("node22/test/parallel/test-https-hwm.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-https-hwm.js"),
        shared_extra_files: COMMON_TLS_SESSION_CERT_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-tls-basic-validations.js"),
    shared_official_batch_case!("test/parallel/test-tls-check-server-identity.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-connect-abort-controller.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-connect-allow-half-open-option.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-tls-connect-hwm-option.js",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some("node22/test/parallel/test-tls-connect-hwm-option.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-tls-connect-hwm-option.js"),
        shared_extra_files: COMMON_TLS_EXTENDED_CERT_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-connect-no-host.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-connect-simple.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-tls-connect-timeout-option.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-options-boolean-check.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-tls-server-parent-constructor-options.js",
        COMMON_TLS_EXTENDED_CERT_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-dgram-bytes-length.js"),
    shared_official_batch_case!("test/parallel/test-dgram-createSocket-type.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-address-types.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-bad-arguments.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-invalid-msg-type.js"),
    shared_official_batch_case!("test/parallel/test-dgram-close-is-not-callback.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-empty-array.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-empty-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-address.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind-default-address.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind.js"),
    shared_official_batch_case!("test/parallel/test-dgram-close.js"),
    shared_official_batch_case!("test/parallel/test-dgram-listen-after-bind.js"),
    shared_official_batch_case!("test/parallel/test-dgram-ref.js"),
    shared_official_batch_case!("test/parallel/test-dgram-unref.js"),
    shared_official_batch_case!("test/parallel/test-dgram-implicit-bind.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-callback-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-callback-buffer-length.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-callback-multi-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-default-host.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-empty-array.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-empty-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-empty-packet.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-callback-buffer-empty-address.js"),
    shared_official_batch_case!(
        "test/parallel/test-dgram-send-callback-buffer-length-empty-address.js"
    ),
    shared_official_batch_case!("test/parallel/test-dgram-send-callback-buffer-length.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-callback-buffer.js"),
    shared_official_batch_case!(
        "test/parallel/test-dgram-send-callback-multi-buffer-empty-address.js"
    ),
    shared_official_batch_case!("test/parallel/test-dgram-send-callback-multi-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-callback-recursive.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-cb-quelches-error.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-default-host.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-empty-packet.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-multi-buffer-copy.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-multi-string-array.js"),
    shared_official_batch_case!("test/parallel/test-dgram-sendto.js"),
    shared_official_batch_case!("test/parallel/test-dgram-abort-closed.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind-error-repeat.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind-fd-error.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind-fd.js"),
    shared_official_batch_case!("test/parallel/test-dgram-bind-socket-close-before-lookup.js"),
    shared_official_batch_case!("test/parallel/test-dgram-blocklist.js"),
    shared_official_batch_case!("test/parallel/test-dgram-close-during-bind.js"),
    shared_official_batch_case!("test/parallel/test-dgram-close-in-listening.js"),
    shared_official_batch_case!("test/parallel/test-dgram-close-signal.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-multi-buffer-copy.js"),
    shared_official_batch_case!("test/parallel/test-dgram-connect-send-multi-string-array.js"),
    shared_official_batch_case!("test/parallel/test-dgram-create-socket-handle-fd.js"),
    shared_official_batch_case!("test/parallel/test-dgram-create-socket-handle.js"),
    shared_official_batch_case!("test/parallel/test-dgram-custom-lookup.js"),
    shared_official_batch_case!("test/parallel/test-dgram-membership.js"),
    shared_official_batch_case!("test/parallel/test-dgram-msgsize.js"),
    shared_official_batch_case!("test/parallel/test-dgram-multicast-loopback.js"),
    shared_official_batch_case!("test/parallel/test-dgram-multicast-set-interface.js"),
    shared_official_batch_case!("test/parallel/test-dgram-multicast-setTTL.js"),
    shared_official_batch_case!("test/parallel/test-dgram-oob-buffer.js"),
    shared_official_batch_case!("test/parallel/test-dgram-recv-error.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-error.js"),
    shared_official_batch_case!("test/parallel/test-dgram-send-queue-info.js"),
    shared_official_batch_case!("test/parallel/test-dgram-setBroadcast.js"),
    shared_official_batch_case!("test/parallel/test-dgram-setTTL.js"),
    shared_official_batch_case!("test/parallel/test-dgram-socket-buffer-size.js"),
    shared_official_batch_case!("test/parallel/test-dgram-udp4.js"),
];
