const PROCESS_AND_TIMING_BATCH: &[NodeCompatBatchEntry] = &[
    shared_official_batch_case!("test/parallel/test-process-default.js"),
    shared_official_batch_case!("test/parallel/test-process-prototype.js"),
    shared_official_batch_case!("test/parallel/test-process-release.js"),
    node22_only_batch_case!(
        "test/parallel/test-process-features.js",
        "node22/test/parallel/test-process-features.js"
    ),
    shared_official_batch_case!("test/parallel/test-process-uptime.js"),
    shared_official_batch_case!("test/parallel/test-process-emitwarning.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-process-warning.js",
        COMMON_HIJACKSTDIO_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-process-no-deprecation.js"),
    shared_official_batch_case!("test/parallel/test-process-env-symbols.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-process-load-env-file.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-process-load-env-file.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-process-load-env-file.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-process-load-env-file.js"),
        shared_extra_files: &[],
        node20_extra_files: NODE20_PROCESS_LOAD_ENV_FILE_EXTRA_FILES,
        node22_extra_files: NODE22_PROCESS_LOAD_ENV_FILE_EXTRA_FILES,
        node24_extra_files: NODE24_PROCESS_LOAD_ENV_FILE_EXTRA_FILES,
    },
    shared_official_batch_case!("test/parallel/test-process-next-tick.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-doesnt-hang.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-errors.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-fixed-queue-regression.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-intentional-starvation.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-ordering.js"),
    shared_official_batch_case!("test/parallel/test-next-tick-ordering2.js"),
    shared_official_batch_case!("test/parallel/test-next-tick.js"),
    shared_official_batch_case!("test/parallel/test-timers.js"),
    shared_official_batch_case!("test/parallel/test-timers-api-refs.js"),
    shared_official_batch_case!("test/parallel/test-timers-args.js"),
    shared_official_batch_case!("test/parallel/test-timers-clear-null-does-not-throw-error.js"),
    shared_official_batch_case!("test/parallel/test-timers-clear-object-does-not-throw-error.js"),
    shared_official_batch_case!("test/parallel/test-timers-clear-timeout-interval-equivalent.js"),
    shared_official_batch_case!("test/parallel/test-timers-clearImmediate.js"),
    shared_official_batch_case!("test/parallel/test-timers-immediate.js"),
    shared_official_batch_case!("test/parallel/test-timers-non-integer-delay.js"),
    shared_official_batch_case!("test/parallel/test-timers-this.js"),
    shared_official_batch_case!("test/parallel/test-timers-throw-when-cb-not-function.js"),
    shared_official_batch_case!("test/parallel/test-timers-zero-timeout.js"),
    shared_official_batch_case!("test/parallel/test-util-deprecate.js"),
    shared_official_batch_case!("test/parallel/test-util-deprecate-invalid-code.js"),
    shared_official_batch_case!("test/parallel/test-util-format.js"),
    shared_official_batch_case!("test/parallel/test-util-inherits.js"),
    shared_official_batch_case!("test/parallel/test-mime-api.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-mime-whatwg.js",
        MIME_WHATWG_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-perf-hooks-usertiming.js"),
    shared_official_batch_case!("test/parallel/test-perf-hooks-histogram.js"),
    node22_only_batch_case!(
        "test/parallel/test-perf-hooks-resourcetiming.js",
        "node22/test/parallel/test-perf-hooks-resourcetiming.js"
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-util-parse-env.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-util-parse-env.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-util-parse-env.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-util-parse-env.js"),
        shared_extra_files: &[],
        node20_extra_files: NODE20_UTIL_PARSE_ENV_EXTRA_FILES,
        node22_extra_files: NODE22_UTIL_PARSE_ENV_EXTRA_FILES,
        node24_extra_files: NODE24_UTIL_PARSE_ENV_EXTRA_FILES,
    },
    shared_official_batch_case!("test/parallel/test-util-text-decoder.js"),
    shared_official_batch_case!("test/parallel/test-util-types-exists.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-has-subscribers.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-object-channel-pub-sub.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-pub-sub.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-safe-subscriber-errors.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-symbol-named.js"),
    shared_official_batch_case!("test/parallel/test-diagnostics-channel-sync-unsubscribe.js"),
];

const STREAMS_AND_LOCAL_IO_BATCH: &[NodeCompatBatchEntry] = &[
    shared_official_batch_case!("test/parallel/test-os-eol.js"),
    shared_official_batch_case!("test/parallel/test-tty-stdin-end.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-tty-stdin-pipe.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-tty-stdin-pipe.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-tty-stdin-pipe.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-tty-stdin-pipe.js"),
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-tty-backwards-api.js"),
    shared_official_batch_case!("test/parallel/test-os-checked-function.js"),
    shared_official_batch_case!("test/parallel/test-ttywrap-invalid-fd.js"),
    shared_official_batch_case!("test/parallel/test-ttywrap-stack.js"),
    shared_official_batch_case!("test/parallel/test-readline-csi.js"),
    shared_official_batch_case!("test/parallel/test-readline-carriage-return-between-chunks.js"),
    shared_official_batch_case!("test/parallel/test-readline-input-onerror.js"),
    shared_official_batch_case!("test/parallel/test-readline-async-iterators.js"),
    shared_official_batch_case!("test/parallel/test-readline-async-iterators-backpressure.js"),
    shared_official_batch_case!("test/parallel/test-readline-async-iterators-destroy.js"),
    shared_official_batch_case!("test/parallel/test-readline-interface.js"),
    shared_official_batch_case!("test/parallel/test-readline-promises-interface.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-readline-promises-csi.mjs",
        node20_fixture_source_path: Some("node20/test/parallel/test-readline-promises-csi.mjs"),
        node22_fixture_source_path: Some("node22/test/parallel/test-readline-promises-csi.mjs"),
        node24_fixture_source_path: Some("node24/test/parallel/test-readline-promises-csi.mjs"),
        shared_extra_files: &[],
        node20_extra_files: NODE20_COMMON_INDEX_MJS_EXTRA_FILES,
        node22_extra_files: NODE22_COMMON_INDEX_MJS_EXTRA_FILES,
        node24_extra_files: NODE24_COMMON_INDEX_MJS_EXTRA_FILES,
    },
    shared_official_batch_case!("test/parallel/test-stream-construct.js"),
    shared_official_batch_case!("test/parallel/test-stream-auto-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex-end.js"),
    shared_official_batch_case!("test/parallel/test-stream-end-of-streams.js"),
    shared_official_batch_case!("test/parallel/test-stream-event-names.js"),
    shared_official_batch_case!("test/parallel/test-stream-end-paused.js"),
    shared_official_batch_case!("test/parallel/test-stream-error-once.js"),
    shared_official_batch_case!("test/parallel/test-stream-events-prepend.js"),
    shared_official_batch_case!("test/parallel/test-stream-inheritance.js"),
    shared_official_batch_case!("test/parallel/test-stream-ispaused.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-aborted.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-constructor-set-methods.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-end-destroyed.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex-props.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex-readable-writable.js"),
    shared_official_batch_case!("test/parallel/test-stream-passthrough-drain.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-after-end.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-await-drain.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-cleanup.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-event.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-flow.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-multiple-pipes.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-ended.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-data.js"),
    shared_official_batch_case!("test/parallel/test-stream-decoder-objectmode.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-event.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-emittedReadable.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-default-encoding.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-invalid-chunk.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-next-no-null.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-no-unneeded-readable.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-pause-and-resume.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-readable.js"),
    shared_official_batch_case!("test/parallel/test-stream-reduce.js"),
    shared_official_batch_case!("test/parallel/test-stream-add-abort-signal.js"),
    shared_official_batch_case!(
        "test/parallel/test-stream-base-prototype-accessors-enumerability.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-catch-rejections.js"),
    shared_official_batch_case!(
        "test/parallel/test-stream-readable-setEncoding-existing-buffers.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-readable-setEncoding-null.js"),
    shared_official_batch_case!("test/parallel/test-stream-map.js"),
    shared_official_batch_case!("test/parallel/test-stream-filter.js"),
    shared_official_batch_case!("test/parallel/test-stream-forEach.js"),
    shared_official_batch_case!("test/parallel/test-stream-toArray.js"),
    shared_official_batch_case!("test/parallel/test-stream-drop-take.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-stream-flatMap.js",
        STREAM_FLATMAP_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-stream-consumers.js"),
    shared_official_batch_case!("test/parallel/test-stream-promises.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipeline-async-iterator.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipeline-duplex.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipeline-listeners.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipeline-uncaught.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipeline-with-empty-string.js"),
    shared_official_batch_case!("test/parallel/test-stream-compose.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-stream-compose-operator.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-stream-compose-operator.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-stream-compose-operator.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-stream-destroy-event-order.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplex-from.js"),
    shared_official_batch_case!("test/parallel/test-stream-duplexpair.js"),
    shared_official_batch_case!("test/parallel/test-stream-set-default-hwm.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-add-chunk-during-data.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-didRead.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-dispose.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-from-web-termination.js"),
    node22_only_batch_case!(
        "test/parallel/test-stream-readable-infinite-read.js",
        "node22/test/parallel/test-stream-readable-infinite-read.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-readable-hwm-0.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-hwm-0-async.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-hwm-0-no-flow-data.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-reading-readingMore.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-flow-recursion.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-needReadable.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-readable-then-resume.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-resumeScheduled.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-resume-hwm.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-strategy-option.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-to-web-termination.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-unshift.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-with-unimplemented-_read.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-emit-readable-short-stream.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-error-end.js"),
    shared_official_batch_case!("test/parallel/test-stream-push-strings.js"),
    shared_official_batch_case!("test/parallel/test-stream-aliases-legacy.js"),
    shared_official_batch_case!(
        "test/parallel/test-stream-await-drain-writers-in-synchronously-recursion-write.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-backpressure.js"),
    shared_official_batch_case!("test/parallel/test-stream-big-packet.js"),
    shared_official_batch_case!("test/parallel/test-stream-big-push.js"),
    shared_official_batch_case!("test/parallel/test-stream-err-multiple-callback-construction.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-deadlock.js"),
    shared_official_batch_case!("test/parallel/test-stream-pipe-same-destination-twice.js"),
    shared_official_batch_case!("test/parallel/test-stream-push-order.js"),
    shared_official_batch_case!("test/parallel/test-stream-readable-object-multi-push-async.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-callback-twice.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-constructor-set-methods.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-final.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-final-sync.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-flush-data.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-hwm0.js"),
    shared_official_batch_case!("test/parallel/test-stream-transform-objectmode-falsey-value.js"),
    node22_only_batch_case!(
        "test/parallel/test-stream-transform-split-highwatermark.js",
        "node22/test/parallel/test-stream-transform-split-highwatermark.js"
    ),
    node22_only_batch_case!(
        "test/parallel/test-stream-transform-split-objectmode.js",
        "node22/test/parallel/test-stream-transform-split-objectmode.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-typedarray.js"),
    shared_official_batch_case!("test/parallel/test-stream-unshift-empty-chunk.js"),
    shared_official_batch_case!("test/parallel/test-stream-unshift-read-race.js"),
    shared_official_batch_case!("test/parallel/test-stream-uint8array.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-aborted.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-change-default-encoding.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-clear-buffer.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-constructor-set-methods.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-decoded-encoding.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-end-cb-error.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-end-cb-uncaught.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-end-multiple.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-final-async.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-final-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-final-throw.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-finish-destroyed.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-finished.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-finished-state.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-invalid-chunk.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-needdrain-state.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-null.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-properties.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-write-cb-error.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-write-cb-twice.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-write-error.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-write-writev-finish.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-writable.js"),
    shared_official_batch_case!("test/parallel/test-stream-writable-ended-state.js"),
    shared_official_batch_case!("test/parallel/test-stream-writableState-ending.js"),
    shared_official_batch_case!(
        "test/parallel/test-stream-writableState-uncorked-bufferedRequestCount.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-write-drain.js"),
    shared_official_batch_case!("test/parallel/test-stream-write-destroy.js"),
    shared_official_batch_case!("test/parallel/test-stream-write-final.js"),
    shared_official_batch_case!("test/parallel/test-stream-writev.js"),
    node22_only_batch_case!(
        "test/parallel/test-stream-duplex-readable-end.js",
        "node22/test/parallel/test-stream-duplex-readable-end.js"
    ),
    shared_official_batch_case!("test/parallel/test-stream-duplex-writable-finished.js"),
    shared_official_batch_case!("test/parallel/test-stream-objectmode-undefined.js"),
    shared_official_batch_case!("test/parallel/test-stream-unpipe-event.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-buffer.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-close.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-constants.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-constants.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-constants.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-append-file-sync.js"),
    shared_official_batch_case!("test/parallel/test-fs-append-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-access.js"),
    shared_official_batch_case!("test/parallel/test-fs-assert-encoding-error.js"),
    shared_official_batch_case!("test/parallel/test-fs-buffertype-writesync.js"),
    shared_official_batch_case!("test/parallel/test-fs-exists.js"),
    shared_official_batch_case!("test/parallel/test-fs-existssync-false.js"),
    shared_official_batch_case!("test/parallel/test-fs-null-bytes.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-whatwg-url.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-empty-buffer.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-zero-length.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-file-assert-encoding.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-file-sync.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-optional-params.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-readfile-empty.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-readfile-fd.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-readfile-flags.js"),
    shared_official_batch_case!("test/parallel/test-fs-readfile.js"),
    shared_official_batch_case!("test/parallel/test-fs-readfile-unlink.js"),
    shared_official_batch_case!("test/parallel/test-fs-readfile-zero-byte-liar.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-readSync-optional-params.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-type.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-readv-promisify.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-readv-promises.js"),
    shared_official_batch_case!("test/parallel/test-fs-readv-sync.js"),
    shared_official_batch_case!("test/parallel/test-fs-readv.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-open-flags.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-open-flags.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-open-flags.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-fs-open-flags.js"),
        shared_extra_files: SHARED_FIXTURES_DIR_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-open-no-close.js"),
    shared_official_batch_case!("test/parallel/test-fs-open-numeric-flags.js"),
    shared_official_batch_case!("test/parallel/test-fs-open-mode-mask.js"),
    shared_official_batch_case!("test/parallel/test-fs-mkdir.js"),
    shared_official_batch_case!("test/parallel/test-fs-mkdir-mode-mask.js"),
    shared_official_batch_case!("test/parallel/test-fs-mkdir-rmdir.js"),
    shared_official_batch_case!("test/parallel/test-fs-chmod.js"),
    shared_official_batch_case!("test/parallel/test-fs-chmod-mask.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-copyfile.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-copyfile-respect-permissions.js"),
    shared_official_batch_case!("test/parallel/test-fs-mkdtemp.js"),
    shared_official_batch_case!("test/parallel/test-fs-mkdtemp-prefix-check.js"),
    shared_official_batch_case!("test/parallel/test-fs-link.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-symlink.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-symlink.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-symlink.js"),
        node24_fixture_source_path: None,
        shared_extra_files: CYCLE_FIXTURES_EXTRA_FILES,
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-realpath-buffer-encoding.js",
        CYCLE_FIXTURES_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-realpath-native.js",
        CYCLE_FIXTURES_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-readdir.js"),
    shared_official_batch_case!("test/parallel/test-fs-readdir-types.js"),
    shared_official_batch_case!("test/parallel/test-fs-readlink-type-check.js"),
    shared_official_batch_case!("test/parallel/test-fs-rename-type-check.js"),
    shared_official_batch_case!("test/parallel/test-fs-unlink-type-check.js"),
    shared_official_batch_case!("test/parallel/test-fs-fchmod.js"),
    shared_official_batch_case!("test/parallel/test-fs-fchown.js"),
    shared_official_batch_case!("test/parallel/test-fs-chown-type-check.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-fsync.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-statfs.js"),
    shared_official_batch_case!("test/parallel/test-fs-timestamp-parsing-error.js"),
    shared_official_batch_case!("test/parallel/test-fs-utimes.js"),
    shared_official_batch_case!("test/parallel/test-fs-non-number-arguments-throw.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-opendir.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-opendir.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-opendir.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-type-check.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-throws-not-found.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-throws-on-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-warns-not-found.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-warns-on-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-sync-warns-not-found.js"),
    shared_official_batch_case!("test/parallel/test-fs-rmdir-recursive-sync-warns-on-file.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-truncate.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-truncate.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-truncate.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-fs-truncate.js"),
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-truncate-sync.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-truncate-sync.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-truncate-sync.js"),
        node24_fixture_source_path: Some("node24/test/parallel/test-fs-truncate-sync.js"),
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-truncate-fd.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-truncate-fd.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-truncate-fd.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-truncate-clear-file-zero.js"),
    node22_only_batch_case!(
        "test/parallel/test-fs-stat.js",
        "node22/test/parallel/test-fs-stat.js"
    ),
    shared_official_batch_case!("test/parallel/test-fs-write-buffer.js"),
    shared_official_batch_case!("test/parallel/test-fs-close-errors.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-file-buffer.js"),
    shared_official_batch_case!("test/parallel/test-fs-writefile-with-fd.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-file-flush.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-file-typedarrays.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-no-fd.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-optional-params.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-negativeoffset.js"),
    shared_official_batch_case!("test/parallel/test-fs-util-validateoffsetlength.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-sync.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-sync-optional-params.js"),
    shared_official_batch_case!("test/parallel/test-fs-writev-promises.js"),
    shared_official_batch_case!("test/parallel/test-fs-writev.js"),
    shared_official_batch_case!("test/parallel/test-fs-writev-sync.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-offset-null.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-promises-optional-params.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-promises-write-optional-params.js"),
    shared_official_batch_case!("test/parallel/test-fs-promisified.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-write.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-append-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-stat.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-chmod.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-truncate.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-promises-file-handle-sync.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-writeFile.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-promises-file-handle-dispose.js",
        node20_fixture_source_path: Some(
            "node20/test/parallel/test-fs-promises-file-handle-dispose.js",
        ),
        node22_fixture_source_path: Some(
            "node22/test/parallel/test-fs-promises-file-handle-dispose.js",
        ),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-stream.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-promises-file-handle-readLines.mjs",
        node20_fixture_source_path: Some(
            "node20/test/parallel/test-fs-promises-file-handle-readLines.mjs",
        ),
        node22_fixture_source_path: Some(
            "node22/test/parallel/test-fs-promises-file-handle-readLines.mjs",
        ),
        node24_fixture_source_path: Some(
            "node24/test/parallel/test-fs-promises-file-handle-readLines.mjs",
        ),
        shared_extra_files: &[],
        node20_extra_files: NODE20_COMMON_INDEX_MJS_EXTRA_FILES,
        node22_extra_files: NODE22_COMMON_INDEX_MJS_EXTRA_FILES,
        node24_extra_files: NODE24_COMMON_INDEX_MJS_EXTRA_FILES,
    },
    shared_official_batch_case!("test/parallel/test-fs-read-stream-file-handle.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-stream-file-handle.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-promises-file-handle-readFile.js",
        COMMON_TICK_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-promises-file-handle-read.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-op-errors.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-aggregate-errors.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-close.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-file-handle-close-errors.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-exists.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-readfile.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-promises-readfile-empty.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-promises-readfile-with-fd.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-writefile-typedarray.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-writefile-with-fd.js"),
    shared_official_batch_case!("test/parallel/test-fs-promises-writefile.js"),
    shared_official_batch_case!("test/parallel/test-fs-append-file-flush.js"),
    shared_official_batch_case!("test/parallel/test-fs-read-stream-fd.js"),
    shared_official_batch_case!("test/parallel/test-fs-read-stream-autoClose.js"),
    shared_official_batch_case!("test/parallel/test-fs-read-stream-double-close.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-empty-readStream.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-read-stream-encoding.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-write-stream.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-write-stream.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-write-stream.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case!("test/parallel/test-fs-write-stream-end.js"),
    shared_official_batch_case!("test/parallel/test-fs-write-stream-double-close.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-write-stream-autoclose-option.js",
        node20_fixture_source_path: Some(
            "node20/test/parallel/test-fs-write-stream-autoclose-option.js",
        ),
        node22_fixture_source_path: Some(
            "node22/test/parallel/test-fs-write-stream-autoclose-option.js",
        ),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-write-stream-encoding.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-ready-event-stream.js"),
    shared_official_batch_case!("test/parallel/test-fs-sync-fd-leak.js"),
    shared_official_batch_case!("test/parallel/test-fs-operations-with-surrogate-pairs.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-symlink-buffer-path.js",
        CYCLE_FIXTURES_EXTRA_FILES
    ),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-glob.mjs",
        node20_fixture_source_path: None,
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-glob.mjs"),
        node24_fixture_source_path: Some("node24/test/parallel/test-fs-glob.mjs"),
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: NODE22_COMMON_INDEX_MJS_EXTRA_FILES,
        node24_extra_files: NODE24_COMMON_INDEX_MJS_EXTRA_FILES,
    },
    shared_official_batch_case!("test/parallel/test-fs-options-immutable.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch.js"),
    shared_official_batch_case_with_extra!(
        "test/parallel/test-fs-watch-abort-signal.js",
        SHARED_FIXTURES_DIR_EXTRA_FILES
    ),
    shared_official_batch_case!("test/parallel/test-fs-watch-ref-unref.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-stop-async.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-stop-sync.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-enoent.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-encoding.js"),
    shared_official_batch_case!("test/parallel/test-fs-watchfile.js"),
    shared_official_batch_case!("test/parallel/test-fs-watchfile-bigint.js"),
    shared_official_batch_case!("test/parallel/test-fs-watchfile-ref-unref.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-file-enoent-after-deletion.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-close-when-destroyed.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-promise.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-add-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-update-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-delete.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-add-folder.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-add-file-with-url.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-validate.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-sync-write.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-add-file-to-new-folder.js"),
    shared_official_batch_case!(
        "test/parallel/test-fs-watch-recursive-add-file-to-existing-subfolder.js"
    ),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-watch-file.js"),
    shared_official_batch_case!("test/parallel/test-fs-watch-recursive-symlink.js"),
    NodeCompatBatchEntry {
        test_relative_path: "test/parallel/test-fs-promises-watch.js",
        node20_fixture_source_path: Some("node20/test/parallel/test-fs-promises-watch.js"),
        node22_fixture_source_path: Some("node22/test/parallel/test-fs-promises-watch.js"),
        node24_fixture_source_path: None,
        shared_extra_files: &[],
        node20_extra_files: &[],
        node22_extra_files: &[],
        node24_extra_files: &[],
    },
];

