ARG FEDORA_VERSION=41
FROM quay.io/fedora/fedora:${FEDORA_VERSION}

RUN dnf install -y rpm-ostree osbuild && dnf clean all -y && rm -rf /var/cache

RUN which osbuild && osbuild --version && rpm-ostree --version
