// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference, makeQueryReference } from "@nimbus/nimbus/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const api = {
  agent: {
    list: makeQueryReference<{
  "conversationId": string;
}, Doc<"messages">[]>("agent:list", "public"),
    listMemory: makeQueryReference<{
  "conversationId": string;
}, Doc<"agentMemory">[]>("agent:listMemory", "public"),
    send: makeMutationReference<{
  "conversationId": string;
  "text": string;
}, {
  "tool": string | null;
}>("agent:send", "public")
  }
};

export const internal = {
  agent: {
    deliverReminder: makeMutationReference<{
  "conversationId": string;
  "text": string;
  "createdAt": number;
}, Id<"messages">>("agent:deliverReminder", "internal")
  }
};
