// Generated by @nimbus/codegen. Do not edit by hand.
import type { GenericId } from "@nimbus/nimbus/values";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type TableNames = "messages" | "agentMemory";

export type Id<TableName extends string> = GenericId<TableName>;

type DocumentByTable = {
  "messages": {
    _id: Id<"messages">;
    _creationTime: number;
    _updateTime: number;
    "conversationId": string;
    "role": string;
    "text": string;
    "tool": string | undefined;
    "createdAt": number;
  };
  "agentMemory": {
    _id: Id<"agentMemory">;
    _creationTime: number;
    _updateTime: number;
    "conversationId": string;
    "text": string;
    "createdAt": number;
  };
};

type IndexNamesByTable = {
  "messages": "by_conversation";
  "agentMemory": "by_conversation";
};

export type Doc<TableName extends TableNames> = DocumentByTable[TableName];

export type DataModel = {
  [TableName in TableNames]: {
    document: DocumentByTable[TableName];
    fieldPaths: keyof DocumentByTable[TableName];
    indexes: IndexNamesByTable[TableName];
  };
};
