// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "@nimbus/nimbus/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const scheduledFunctions = {
  agent: {
    send: makeMutationReference<{
  "conversationId": string;
  "text": string;
}, {
  "tool": string | null;
}>("agent:send", "public")
  }
};

export const internalScheduledFunctions = {
  agent: {
    deliverReminder: makeMutationReference<{
  "conversationId": string;
  "text": string;
  "createdAt": number;
}, Id<"messages">>("agent:deliverReminder", "internal")
  }
};
