/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeveloperIndexRouteImport } from './routes/developer/index'
import { Route as DeveloperComputeRouteImport } from './routes/developer/compute'
import { Route as DeveloperFilesRouteImport } from './routes/developer/files'
import { Route as DeveloperObservabilityRouteImport } from './routes/developer/observability'
import { Route as DeveloperSchedulesRouteImport } from './routes/developer/schedules'
import { Route as DeveloperServicesRouteImport } from './routes/developer/services'
import { Route as DeveloperSettingsRouteImport } from './routes/developer/settings'
import { Route as DeveloperStorageRouteImport } from './routes/developer/storage'
import { Route as OperatorIndexRouteImport } from './routes/operator/index'
import { Route as OperatorMachinesRouteImport } from './routes/operator/machines'
import { Route as OperatorNetworkRouteImport } from './routes/operator/network'
import { Route as OperatorObservabilityRouteImport } from './routes/operator/observability'
import { Route as OperatorServicesRouteImport } from './routes/operator/services'
import { Route as OperatorSettingsRouteImport } from './routes/operator/settings'
import { Route as OperatorTenantsRouteImport } from './routes/operator/tenants'
import { Route as DeveloperComputeFunctionRouteImport } from './routes/developer/compute_.$function'
import { Route as DeveloperServicesServiceRouteImport } from './routes/developer/services_.$service'
import { Route as DeveloperStorageTableRouteImport } from './routes/developer/storage_.$table'
import { Route as OperatorServicesServiceRouteImport } from './routes/operator/services_.$service'
import { Route as DeveloperComputeRunsRunIdRouteImport } from './routes/developer/compute_.runs_.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/developer/',
  path: '/developer/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperComputeRoute = DeveloperComputeRouteImport.update({
  id: '/developer/compute',
  path: '/developer/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperFilesRoute = DeveloperFilesRouteImport.update({
  id: '/developer/files',
  path: '/developer/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperObservabilityRoute = DeveloperObservabilityRouteImport.update({
  id: '/developer/observability',
  path: '/developer/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSchedulesRoute = DeveloperSchedulesRouteImport.update({
  id: '/developer/schedules',
  path: '/developer/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperServicesRoute = DeveloperServicesRouteImport.update({
  id: '/developer/services',
  path: '/developer/services',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSettingsRoute = DeveloperSettingsRouteImport.update({
  id: '/developer/settings',
  path: '/developer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperStorageRoute = DeveloperStorageRouteImport.update({
  id: '/developer/storage',
  path: '/developer/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorMachinesRoute = OperatorMachinesRouteImport.update({
  id: '/operator/machines',
  path: '/operator/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorNetworkRoute = OperatorNetworkRouteImport.update({
  id: '/operator/network',
  path: '/operator/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorObservabilityRoute = OperatorObservabilityRouteImport.update({
  id: '/operator/observability',
  path: '/operator/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorServicesRoute = OperatorServicesRouteImport.update({
  id: '/operator/services',
  path: '/operator/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorSettingsRoute = OperatorSettingsRouteImport.update({
  id: '/operator/settings',
  path: '/operator/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorTenantsRoute = OperatorTenantsRouteImport.update({
  id: '/operator/tenants',
  path: '/operator/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperComputeFunctionRoute =
  DeveloperComputeFunctionRouteImport.update({
    id: '/developer/compute_/$function',
    path: '/developer/compute/$function',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperServicesServiceRoute =
  DeveloperServicesServiceRouteImport.update({
    id: '/developer/services_/$service',
    path: '/developer/services/$service',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeveloperStorageTableRoute = DeveloperStorageTableRouteImport.update({
  id: '/developer/storage_/$table',
  path: '/developer/storage/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorServicesServiceRoute = OperatorServicesServiceRouteImport.update({
  id: '/operator/services_/$service',
  path: '/operator/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperComputeRunsRunIdRoute =
  DeveloperComputeRunsRunIdRouteImport.update({
    id: '/developer/compute_/runs_/$runId',
    path: '/developer/compute/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/developer/compute': typeof DeveloperComputeRoute
  '/developer/files': typeof DeveloperFilesRoute
  '/developer/observability': typeof DeveloperObservabilityRoute
  '/developer/schedules': typeof DeveloperSchedulesRoute
  '/developer/services': typeof DeveloperServicesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/storage': typeof DeveloperStorageRoute
  '/operator/machines': typeof OperatorMachinesRoute
  '/operator/network': typeof OperatorNetworkRoute
  '/operator/observability': typeof OperatorObservabilityRoute
  '/operator/services': typeof OperatorServicesRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/tenants': typeof OperatorTenantsRoute
  '/developer/': typeof DeveloperIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/developer/compute/$function': typeof DeveloperComputeFunctionRoute
  '/developer/services/$service': typeof DeveloperServicesServiceRoute
  '/developer/storage/$table': typeof DeveloperStorageTableRoute
  '/operator/services/$service': typeof OperatorServicesServiceRoute
  '/developer/compute/runs/$runId': typeof DeveloperComputeRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/developer/compute': typeof DeveloperComputeRoute
  '/developer/files': typeof DeveloperFilesRoute
  '/developer/observability': typeof DeveloperObservabilityRoute
  '/developer/schedules': typeof DeveloperSchedulesRoute
  '/developer/services': typeof DeveloperServicesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/storage': typeof DeveloperStorageRoute
  '/operator/machines': typeof OperatorMachinesRoute
  '/operator/network': typeof OperatorNetworkRoute
  '/operator/observability': typeof OperatorObservabilityRoute
  '/operator/services': typeof OperatorServicesRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/tenants': typeof OperatorTenantsRoute
  '/developer': typeof DeveloperIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/developer/compute/$function': typeof DeveloperComputeFunctionRoute
  '/developer/services/$service': typeof DeveloperServicesServiceRoute
  '/developer/storage/$table': typeof DeveloperStorageTableRoute
  '/operator/services/$service': typeof OperatorServicesServiceRoute
  '/developer/compute/runs/$runId': typeof DeveloperComputeRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/developer/compute': typeof DeveloperComputeRoute
  '/developer/files': typeof DeveloperFilesRoute
  '/developer/observability': typeof DeveloperObservabilityRoute
  '/developer/schedules': typeof DeveloperSchedulesRoute
  '/developer/services': typeof DeveloperServicesRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/storage': typeof DeveloperStorageRoute
  '/operator/machines': typeof OperatorMachinesRoute
  '/operator/network': typeof OperatorNetworkRoute
  '/operator/observability': typeof OperatorObservabilityRoute
  '/operator/services': typeof OperatorServicesRoute
  '/operator/settings': typeof OperatorSettingsRoute
  '/operator/tenants': typeof OperatorTenantsRoute
  '/developer/': typeof DeveloperIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/developer/compute_/$function': typeof DeveloperComputeFunctionRoute
  '/developer/services_/$service': typeof DeveloperServicesServiceRoute
  '/developer/storage_/$table': typeof DeveloperStorageTableRoute
  '/operator/services_/$service': typeof OperatorServicesServiceRoute
  '/developer/compute_/runs_/$runId': typeof DeveloperComputeRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/developer/compute'
    | '/developer/files'
    | '/developer/observability'
    | '/developer/schedules'
    | '/developer/services'
    | '/developer/settings'
    | '/developer/storage'
    | '/operator/machines'
    | '/operator/network'
    | '/operator/observability'
    | '/operator/services'
    | '/operator/settings'
    | '/operator/tenants'
    | '/developer/'
    | '/operator/'
    | '/developer/compute/$function'
    | '/developer/services/$service'
    | '/developer/storage/$table'
    | '/operator/services/$service'
    | '/developer/compute/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/developer/compute'
    | '/developer/files'
    | '/developer/observability'
    | '/developer/schedules'
    | '/developer/services'
    | '/developer/settings'
    | '/developer/storage'
    | '/operator/machines'
    | '/operator/network'
    | '/operator/observability'
    | '/operator/services'
    | '/operator/settings'
    | '/operator/tenants'
    | '/developer'
    | '/operator'
    | '/developer/compute/$function'
    | '/developer/services/$service'
    | '/developer/storage/$table'
    | '/operator/services/$service'
    | '/developer/compute/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/developer/compute'
    | '/developer/files'
    | '/developer/observability'
    | '/developer/schedules'
    | '/developer/services'
    | '/developer/settings'
    | '/developer/storage'
    | '/operator/machines'
    | '/operator/network'
    | '/operator/observability'
    | '/operator/services'
    | '/operator/settings'
    | '/operator/tenants'
    | '/developer/'
    | '/operator/'
    | '/developer/compute_/$function'
    | '/developer/services_/$service'
    | '/developer/storage_/$table'
    | '/operator/services_/$service'
    | '/developer/compute_/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeveloperComputeRoute: typeof DeveloperComputeRoute
  DeveloperFilesRoute: typeof DeveloperFilesRoute
  DeveloperObservabilityRoute: typeof DeveloperObservabilityRoute
  DeveloperSchedulesRoute: typeof DeveloperSchedulesRoute
  DeveloperServicesRoute: typeof DeveloperServicesRoute
  DeveloperSettingsRoute: typeof DeveloperSettingsRoute
  DeveloperStorageRoute: typeof DeveloperStorageRoute
  OperatorMachinesRoute: typeof OperatorMachinesRoute
  OperatorNetworkRoute: typeof OperatorNetworkRoute
  OperatorObservabilityRoute: typeof OperatorObservabilityRoute
  OperatorServicesRoute: typeof OperatorServicesRoute
  OperatorSettingsRoute: typeof OperatorSettingsRoute
  OperatorTenantsRoute: typeof OperatorTenantsRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  DeveloperComputeFunctionRoute: typeof DeveloperComputeFunctionRoute
  DeveloperServicesServiceRoute: typeof DeveloperServicesServiceRoute
  DeveloperStorageTableRoute: typeof DeveloperStorageTableRoute
  OperatorServicesServiceRoute: typeof OperatorServicesServiceRoute
  DeveloperComputeRunsRunIdRoute: typeof DeveloperComputeRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/': {
      id: '/developer/'
      path: '/developer'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/compute': {
      id: '/developer/compute'
      path: '/developer/compute'
      fullPath: '/developer/compute'
      preLoaderRoute: typeof DeveloperComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/files': {
      id: '/developer/files'
      path: '/developer/files'
      fullPath: '/developer/files'
      preLoaderRoute: typeof DeveloperFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/observability': {
      id: '/developer/observability'
      path: '/developer/observability'
      fullPath: '/developer/observability'
      preLoaderRoute: typeof DeveloperObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/schedules': {
      id: '/developer/schedules'
      path: '/developer/schedules'
      fullPath: '/developer/schedules'
      preLoaderRoute: typeof DeveloperSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/services': {
      id: '/developer/services'
      path: '/developer/services'
      fullPath: '/developer/services'
      preLoaderRoute: typeof DeveloperServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/settings': {
      id: '/developer/settings'
      path: '/developer/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof DeveloperSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/storage': {
      id: '/developer/storage'
      path: '/developer/storage'
      fullPath: '/developer/storage'
      preLoaderRoute: typeof DeveloperStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/machines': {
      id: '/operator/machines'
      path: '/operator/machines'
      fullPath: '/operator/machines'
      preLoaderRoute: typeof OperatorMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/network': {
      id: '/operator/network'
      path: '/operator/network'
      fullPath: '/operator/network'
      preLoaderRoute: typeof OperatorNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/observability': {
      id: '/operator/observability'
      path: '/operator/observability'
      fullPath: '/operator/observability'
      preLoaderRoute: typeof OperatorObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/services': {
      id: '/operator/services'
      path: '/operator/services'
      fullPath: '/operator/services'
      preLoaderRoute: typeof OperatorServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/settings': {
      id: '/operator/settings'
      path: '/operator/settings'
      fullPath: '/operator/settings'
      preLoaderRoute: typeof OperatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/tenants': {
      id: '/operator/tenants'
      path: '/operator/tenants'
      fullPath: '/operator/tenants'
      preLoaderRoute: typeof OperatorTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/compute_/$function': {
      id: '/developer/compute_/$function'
      path: '/developer/compute/$function'
      fullPath: '/developer/compute/$function'
      preLoaderRoute: typeof DeveloperComputeFunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/services_/$service': {
      id: '/developer/services_/$service'
      path: '/developer/services/$service'
      fullPath: '/developer/services/$service'
      preLoaderRoute: typeof DeveloperServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/storage_/$table': {
      id: '/developer/storage_/$table'
      path: '/developer/storage/$table'
      fullPath: '/developer/storage/$table'
      preLoaderRoute: typeof DeveloperStorageTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/services_/$service': {
      id: '/operator/services_/$service'
      path: '/operator/services/$service'
      fullPath: '/operator/services/$service'
      preLoaderRoute: typeof OperatorServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/compute_/runs_/$runId': {
      id: '/developer/compute_/runs_/$runId'
      path: '/developer/compute/runs/$runId'
      fullPath: '/developer/compute/runs/$runId'
      preLoaderRoute: typeof DeveloperComputeRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeveloperComputeRoute: DeveloperComputeRoute,
  DeveloperFilesRoute: DeveloperFilesRoute,
  DeveloperObservabilityRoute: DeveloperObservabilityRoute,
  DeveloperSchedulesRoute: DeveloperSchedulesRoute,
  DeveloperServicesRoute: DeveloperServicesRoute,
  DeveloperSettingsRoute: DeveloperSettingsRoute,
  DeveloperStorageRoute: DeveloperStorageRoute,
  OperatorMachinesRoute: OperatorMachinesRoute,
  OperatorNetworkRoute: OperatorNetworkRoute,
  OperatorObservabilityRoute: OperatorObservabilityRoute,
  OperatorServicesRoute: OperatorServicesRoute,
  OperatorSettingsRoute: OperatorSettingsRoute,
  OperatorTenantsRoute: OperatorTenantsRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  DeveloperComputeFunctionRoute: DeveloperComputeFunctionRoute,
  DeveloperServicesServiceRoute: DeveloperServicesServiceRoute,
  DeveloperStorageTableRoute: DeveloperStorageTableRoute,
  OperatorServicesServiceRoute: OperatorServicesServiceRoute,
  DeveloperComputeRunsRunIdRoute: DeveloperComputeRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
