/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StorageTenantRouteImport } from './routes/storage_.$tenant'
import { Route as ComputeRunnerRouteImport } from './routes/compute_.runner'
import { Route as StorageTenantTableRouteImport } from './routes/storage_.$tenant_.$table'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageTenantRoute = StorageTenantRouteImport.update({
  id: '/storage_/$tenant',
  path: '/storage/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRunnerRoute = ComputeRunnerRouteImport.update({
  id: '/compute_/runner',
  path: '/compute/runner',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageTenantTableRoute = StorageTenantTableRouteImport.update({
  id: '/storage_/$tenant_/$table',
  path: '/storage/$tenant/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/machines': typeof MachinesRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/compute/runner': typeof ComputeRunnerRoute
  '/storage/$tenant': typeof StorageTenantRoute
  '/storage/$tenant/$table': typeof StorageTenantTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/machines': typeof MachinesRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/compute/runner': typeof ComputeRunnerRoute
  '/storage/$tenant': typeof StorageTenantRoute
  '/storage/$tenant/$table': typeof StorageTenantTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compute': typeof ComputeRoute
  '/machines': typeof MachinesRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/compute_/runner': typeof ComputeRunnerRoute
  '/storage_/$tenant': typeof StorageTenantRoute
  '/storage_/$tenant_/$table': typeof StorageTenantTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compute'
    | '/machines'
    | '/network'
    | '/observability'
    | '/settings'
    | '/storage'
    | '/compute/runner'
    | '/storage/$tenant'
    | '/storage/$tenant/$table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compute'
    | '/machines'
    | '/network'
    | '/observability'
    | '/settings'
    | '/storage'
    | '/compute/runner'
    | '/storage/$tenant'
    | '/storage/$tenant/$table'
  id:
    | '__root__'
    | '/'
    | '/compute'
    | '/machines'
    | '/network'
    | '/observability'
    | '/settings'
    | '/storage'
    | '/compute_/runner'
    | '/storage_/$tenant'
    | '/storage_/$tenant_/$table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeRoute: typeof ComputeRoute
  MachinesRoute: typeof MachinesRoute
  NetworkRoute: typeof NetworkRoute
  ObservabilityRoute: typeof ObservabilityRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  ComputeRunnerRoute: typeof ComputeRunnerRoute
  StorageTenantRoute: typeof StorageTenantRoute
  StorageTenantTableRoute: typeof StorageTenantTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage_/$tenant': {
      id: '/storage_/$tenant'
      path: '/storage/$tenant'
      fullPath: '/storage/$tenant'
      preLoaderRoute: typeof StorageTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute_/runner': {
      id: '/compute_/runner'
      path: '/compute/runner'
      fullPath: '/compute/runner'
      preLoaderRoute: typeof ComputeRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage_/$tenant_/$table': {
      id: '/storage_/$tenant_/$table'
      path: '/storage/$tenant/$table'
      fullPath: '/storage/$tenant/$table'
      preLoaderRoute: typeof StorageTenantTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeRoute: ComputeRoute,
  MachinesRoute: MachinesRoute,
  NetworkRoute: NetworkRoute,
  ObservabilityRoute: ObservabilityRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  ComputeRunnerRoute: ComputeRunnerRoute,
  StorageTenantRoute: StorageTenantRoute,
  StorageTenantTableRoute: StorageTenantTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
