/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppStorageRouteImport } from './routes/app/storage'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppSchedulesRouteImport } from './routes/app/schedules'
import { Route as AppObservabilityRouteImport } from './routes/app/observability'
import { Route as AppFilesRouteImport } from './routes/app/files'
import { Route as AppComputeRouteImport } from './routes/app/compute'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminObservabilityRouteImport } from './routes/admin/observability'
import { Route as AdminNetworkRouteImport } from './routes/admin/network'
import { Route as AdminMachinesRouteImport } from './routes/admin/machines'
import { Route as AppStorageTableRouteImport } from './routes/app/storage_.$table'
import { Route as AppComputeRunnerRouteImport } from './routes/app/compute_.runner'
import { Route as AppComputeRunsRunIdRouteImport } from './routes/app/compute_.runs_.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/app/storage',
  path: '/app/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSchedulesRoute = AppSchedulesRouteImport.update({
  id: '/app/schedules',
  path: '/app/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const AppObservabilityRoute = AppObservabilityRouteImport.update({
  id: '/app/observability',
  path: '/app/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/app/files',
  path: '/app/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComputeRoute = AppComputeRouteImport.update({
  id: '/app/compute',
  path: '/app/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/admin/observability',
  path: '/admin/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNetworkRoute = AdminNetworkRouteImport.update({
  id: '/admin/network',
  path: '/admin/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMachinesRoute = AdminMachinesRouteImport.update({
  id: '/admin/machines',
  path: '/admin/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStorageTableRoute = AppStorageTableRouteImport.update({
  id: '/app/storage_/$table',
  path: '/app/storage/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComputeRunnerRoute = AppComputeRunnerRouteImport.update({
  id: '/app/compute_/runner',
  path: '/app/compute/runner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComputeRunsRunIdRoute = AppComputeRunsRunIdRouteImport.update({
  id: '/app/compute_/runs_/$runId',
  path: '/app/compute/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/compute': typeof AppComputeRoute
  '/app/files': typeof AppFilesRoute
  '/app/observability': typeof AppObservabilityRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/storage': typeof AppStorageRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/compute/runner': typeof AppComputeRunnerRoute
  '/app/storage/$table': typeof AppStorageTableRoute
  '/app/compute/runs/$runId': typeof AppComputeRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/compute': typeof AppComputeRoute
  '/app/files': typeof AppFilesRoute
  '/app/observability': typeof AppObservabilityRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/storage': typeof AppStorageRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/compute/runner': typeof AppComputeRunnerRoute
  '/app/storage/$table': typeof AppStorageTableRoute
  '/app/compute/runs/$runId': typeof AppComputeRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/machines': typeof AdminMachinesRoute
  '/admin/network': typeof AdminNetworkRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/compute': typeof AppComputeRoute
  '/app/files': typeof AppFilesRoute
  '/app/observability': typeof AppObservabilityRoute
  '/app/schedules': typeof AppSchedulesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/storage': typeof AppStorageRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/compute_/runner': typeof AppComputeRunnerRoute
  '/app/storage_/$table': typeof AppStorageTableRoute
  '/app/compute_/runs_/$runId': typeof AppComputeRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/machines'
    | '/admin/network'
    | '/admin/observability'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/compute'
    | '/app/files'
    | '/app/observability'
    | '/app/schedules'
    | '/app/settings'
    | '/app/storage'
    | '/admin/'
    | '/app/'
    | '/app/compute/runner'
    | '/app/storage/$table'
    | '/app/compute/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/machines'
    | '/admin/network'
    | '/admin/observability'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/compute'
    | '/app/files'
    | '/app/observability'
    | '/app/schedules'
    | '/app/settings'
    | '/app/storage'
    | '/admin'
    | '/app'
    | '/app/compute/runner'
    | '/app/storage/$table'
    | '/app/compute/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/admin/machines'
    | '/admin/network'
    | '/admin/observability'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/tenants'
    | '/app/compute'
    | '/app/files'
    | '/app/observability'
    | '/app/schedules'
    | '/app/settings'
    | '/app/storage'
    | '/admin/'
    | '/app/'
    | '/app/compute_/runner'
    | '/app/storage_/$table'
    | '/app/compute_/runs_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminMachinesRoute: typeof AdminMachinesRoute
  AdminNetworkRoute: typeof AdminNetworkRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AppComputeRoute: typeof AppComputeRoute
  AppFilesRoute: typeof AppFilesRoute
  AppObservabilityRoute: typeof AppObservabilityRoute
  AppSchedulesRoute: typeof AppSchedulesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStorageRoute: typeof AppStorageRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  AppComputeRunnerRoute: typeof AppComputeRunnerRoute
  AppStorageTableRoute: typeof AppStorageTableRoute
  AppComputeRunsRunIdRoute: typeof AppComputeRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/storage': {
      id: '/app/storage'
      path: '/app/storage'
      fullPath: '/app/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedules': {
      id: '/app/schedules'
      path: '/app/schedules'
      fullPath: '/app/schedules'
      preLoaderRoute: typeof AppSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/observability': {
      id: '/app/observability'
      path: '/app/observability'
      fullPath: '/app/observability'
      preLoaderRoute: typeof AppObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/files': {
      id: '/app/files'
      path: '/app/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/compute': {
      id: '/app/compute'
      path: '/app/compute'
      fullPath: '/app/compute'
      preLoaderRoute: typeof AppComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/observability': {
      id: '/admin/observability'
      path: '/admin/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/network': {
      id: '/admin/network'
      path: '/admin/network'
      fullPath: '/admin/network'
      preLoaderRoute: typeof AdminNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/machines': {
      id: '/admin/machines'
      path: '/admin/machines'
      fullPath: '/admin/machines'
      preLoaderRoute: typeof AdminMachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/storage_/$table': {
      id: '/app/storage_/$table'
      path: '/app/storage/$table'
      fullPath: '/app/storage/$table'
      preLoaderRoute: typeof AppStorageTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/compute_/runner': {
      id: '/app/compute_/runner'
      path: '/app/compute/runner'
      fullPath: '/app/compute/runner'
      preLoaderRoute: typeof AppComputeRunnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/compute_/runs_/$runId': {
      id: '/app/compute_/runs_/$runId'
      path: '/app/compute/runs/$runId'
      fullPath: '/app/compute/runs/$runId'
      preLoaderRoute: typeof AppComputeRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminMachinesRoute: AdminMachinesRoute,
  AdminNetworkRoute: AdminNetworkRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AppComputeRoute: AppComputeRoute,
  AppFilesRoute: AppFilesRoute,
  AppObservabilityRoute: AppObservabilityRoute,
  AppSchedulesRoute: AppSchedulesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStorageRoute: AppStorageRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  AppComputeRunnerRoute: AppComputeRunnerRoute,
  AppStorageTableRoute: AppStorageTableRoute,
  AppComputeRunsRunIdRoute: AppComputeRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
