import {
  buildFunctionIndex,
  ensureModuleTree,
  helperCall,
  helperName,
  renderDocumentType,
  renderIndexUnion,
  renderObjectBlock,
  renderTableNames,
  renderTree,
} from "./type_helpers.mjs";

function generateApiFile(modules, schema, packageNamespace) {
  const publicTree = {};
  const internalTree = {};
  const usedHelpers = new Set();
  const functionIndex = buildFunctionIndex(modules);
  const audit = [];

  for (const moduleInfo of modules) {
    for (const fn of moduleInfo.functions) {
      if (fn.kind === "http_action") {
        continue;
      }

      usedHelpers.add(fn.kind);
      const targetTree = fn.visibility === "internal" ? internalTree : publicTree;
      const moduleNode = ensureModuleTree(targetTree, moduleInfo.moduleName);
      moduleNode[fn.exportName] = helperCall(fn, schema, functionIndex, audit);
    }
  }

  const helperImports = Array.from(usedHelpers)
    .sort()
    .map((kind) => helperName(kind))
    .join(", ");

  return `// Generated by @nimbus/codegen. Do not edit by hand.\n${renderAuditComment(audit)}import { ${helperImports} } from "${packageNamespace}/browser";\nimport type { Doc, Id, JsonValue } from "./dataModel.js";\n\nexport const api = ${renderTree(
    publicTree,
    0,
  )};\n\nexport const internal = ${renderTree(internalTree, 0)};\n`;
}

// The require()-facing counterpart of generateApiFile, emitted only when
// convex.json sets generateCommonJSApi: true (per
// https://docs.convex.dev/client/javascript/node). It carries the same
// function-reference tree as api.ts but as untyped CommonJS, so it cannot
// reuse helperCall's TypeScript generic type arguments.
function generateApiCjsFile(modules, packageNamespace) {
  const publicTree = {};
  const internalTree = {};
  const usedHelpers = new Set();

  for (const moduleInfo of modules) {
    for (const fn of moduleInfo.functions) {
      if (fn.kind === "http_action") {
        continue;
      }

      usedHelpers.add(fn.kind);
      const targetTree = fn.visibility === "internal" ? internalTree : publicTree;
      const moduleNode = ensureModuleTree(targetTree, moduleInfo.moduleName);
      moduleNode[fn.exportName] =
        `${helperName(fn.kind)}(${JSON.stringify(fn.name)}, ${JSON.stringify(fn.visibility)})`;
    }
  }

  const helperImports = Array.from(usedHelpers)
    .sort()
    .map((kind) => helperName(kind))
    .join(", ");

  return `// Generated by @nimbus/codegen. Do not edit by hand.\n"use strict";\n\nconst { ${helperImports} } = require(${JSON.stringify(`${packageNamespace}/browser`)});\n\nconst api = ${renderTree(
    publicTree,
    0,
  )};\n\nconst internal = ${renderTree(internalTree, 0)};\n\nmodule.exports = { api, internal };\n`;
}

function renderAuditComment(audit) {
  if (audit.length === 0) {
    return "";
  }
  const sorted = audit
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name));
  const lines = sorted.map((entry) => `//   ${entry.name} (${entry.source})`);
  return `// Inference audit — handlers whose return type came from a fallback or\n// from a module/export-name convention rather than an informative validator\n// or a readable query plan. Tighten the handler's \`returns:\` validator or\n// register a query plan the codegen can read to drop the entry.\n${lines.join("\n")}\n\n`;
}

function generateServerFile(packageNamespace) {
  return `// Generated by @nimbus/codegen. Do not edit by hand.\nexport {\n  action,\n  defineSchema,\n  defineTable,\n  httpAction,\n  httpRouter,\n  internalAction,\n  internalMutation,\n  internalPaginatedQuery,\n  internalQuery,\n  mutation,\n  paginatedQuery,\n  query,\n} from "${packageNamespace}/server";\nexport type { ActionCtx, MutationCtx, QueryCtx } from "${packageNamespace}/server";\n`;
}

function generateScheduledFunctionsFile(modules, schema, packageNamespace) {
  const publicTree = {};
  const internalTree = {};
  const functionIndex = buildFunctionIndex(modules);

  for (const moduleInfo of modules) {
    for (const fn of moduleInfo.functions) {
      if (fn.kind !== "mutation") {
        continue;
      }

      const targetTree = fn.visibility === "internal" ? internalTree : publicTree;
      const moduleNode = ensureModuleTree(targetTree, moduleInfo.moduleName);
      moduleNode[fn.exportName] = helperCall(fn, schema, functionIndex, undefined);
    }
  }

  return `// Generated by @nimbus/codegen. Do not edit by hand.\nimport { makeMutationReference } from "${packageNamespace}/browser";\nimport type { Doc, Id, JsonValue } from "./dataModel.js";\n\nexport const scheduledFunctions = ${renderTree(
    publicTree,
    0,
  )};\n\nexport const internalScheduledFunctions = ${renderTree(internalTree, 0)};\n`;
}

function generateDataModelFile(schema, packageNamespace) {
  const tableNames = Object.keys(schema.tables);
  const documentEntries = tableNames.map((tableName) => {
    const documentType = renderDocumentType(tableName, schema.tables[tableName].fields, 2);
    return `  ${JSON.stringify(tableName)}: ${documentType};`;
  });
  const indexEntries = tableNames.map((tableName) => {
    const indexes = schema.tables[tableName].indexes;
    return `  ${JSON.stringify(tableName)}: ${renderIndexUnion(indexes)};`;
  });

  return `// Generated by @nimbus/codegen. Do not edit by hand.\nimport type { GenericId } from "${packageNamespace}/values";\n\nexport type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\nexport type TableNames = ${renderTableNames(tableNames)};\n\nexport type Id<TableName extends string> = GenericId<TableName>;\n\ntype DocumentByTable = ${renderObjectBlock(documentEntries)};\n\ntype IndexNamesByTable = ${renderObjectBlock(indexEntries)};\n\nexport type Doc<TableName extends TableNames> = DocumentByTable[TableName];\n\nexport type DataModel = {\n  [TableName in TableNames]: {\n    document: DocumentByTable[TableName];\n    fieldPaths: keyof DocumentByTable[TableName];\n    indexes: IndexNamesByTable[TableName];\n  };\n};\n`;
}

export {
  generateApiCjsFile,
  generateApiFile,
  generateDataModelFile,
  generateScheduledFunctionsFile,
  generateServerFile,
};
