// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel";

export const scheduledFunctions = {
  messages: {
    send: makeMutationReference<{
  "author": string;
  "body": string;
}, Id<"messages">>("messages:send", "public")
  }
};

export const internalScheduledFunctions = {};
