// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference, makeQueryReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel";

export const api = {
  tasks: {
    list: makeQueryReference<{}, Doc<"tasks">[]>("tasks:list", "public"),
    create: makeMutationReference<{
  "text": string;
}, Id<"tasks">>("tasks:create", "public"),
    toggle: makeMutationReference<{
  "id": Id<"tasks">;
}, null>("tasks:toggle", "public"),
    remove: makeMutationReference<{
  "id": Id<"tasks">;
}, null>("tasks:remove", "public")
  }
};

export const internal = {};
