[package]
name = "nimbus-adapters"
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true
license-file.workspace = true

[features]
default = []
cloud-functions = ["dep:nimbus-cloud-functions"]
convex = ["dep:nimbus-convex"]
dynamodb = ["dep:nimbus-dynamodb"]
firebase = ["dep:nimbus-firebase"]
mongodb = ["dep:nimbus-mongodb"]
s3 = ["dep:nimbus-s3"]

[dependencies]
nimbus-cloud-functions = { path = "../nimbus-cloud-functions", optional = true }
nimbus-convex = { path = "../nimbus-convex", optional = true }
nimbus-dynamodb = { path = "../nimbus-dynamodb", optional = true }
nimbus-firebase = { path = "../nimbus-firebase", optional = true }
nimbus-mongodb = { path = "../nimbus-mongodb", optional = true }
nimbus-s3 = { path = "../nimbus-s3", optional = true }

[lints]
workspace = true
