// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference, makeQueryReference } from "@nimbus/nimbus/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const api = {
  worker: {
    list: makeQueryReference<{}, Doc<"jobs">[]>("worker:list", "public"),
    enqueue: makeMutationReference<{
  "label": string;
}, Id<"jobs">>("worker:enqueue", "public"),
    runWorker: makeMutationReference<{
  "jobIds": (Id<"jobs">)[];
  "intervalMs": number;
}, {
  "scheduled": number;
}>("worker:runWorker", "public")
  }
};

export const internal = {
  worker: {
    processJob: makeMutationReference<{
  "jobId": Id<"jobs">;
  "completedAt": number;
}, Id<"jobs">>("worker:processJob", "internal")
  }
};
