// Generated by @nimbus/codegen. Do not edit by hand.
// Inference audit — handlers whose return type came from a fallback or
// from a module/export-name convention rather than an informative validator
// or a readable query plan. Tighten the handler's `returns:` validator or
// register a query plan the codegen can read to drop the entry.
//   adapter_capabilities:list (convention-inferred)
//   bundles:list (convention-inferred)
//   cron_jobs:list (convention-inferred)
//   events:recent (convention-inferred)
//   functions:list (convention-inferred)
//   listeners:list (convention-inferred)
//   machines:list (convention-inferred)
//   ports:list (convention-inferred)
//   routes:list (convention-inferred)
//   runs:recent (convention-inferred)
//   scheduled_jobs:list (convention-inferred)
//   services:list (convention-inferred)
//   subscriptions:list (convention-inferred)
//   tables:list (convention-inferred)

import { makeQueryReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const api = {
  adapter_capabilities: {
    list: makeQueryReference<{
  "adapter": string | null;
  "status": string | null;
  "limit": number | null;
}, Doc<"adapter_capabilities">[]>("adapter_capabilities:list", "public")
  },
  bundles: {
    list: makeQueryReference<{
  "status": string | null;
  "limit": number | null;
}, Doc<"bundles">[]>("bundles:list", "public"),
    bySha256: makeQueryReference<{
  "sha256": string;
}, Doc<"bundles"> | null>("bundles:bySha256", "public")
  },
  cron_jobs: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "status": string | null;
  "limit": number | null;
}, Doc<"cron_jobs">[]>("cron_jobs:list", "public")
  },
  events: {
    recent: makeQueryReference<{
  "source": string | null;
  "level": string | null;
  "category": string | null;
  "correlationId": string | null;
  "limit": number | null;
}, Doc<"events">[]>("events:recent", "public")
  },
  functions: {
    list: makeQueryReference<{
  "bundleId": string | null;
  "kind": string | null;
  "limit": number | null;
}, Doc<"functions">[]>("functions:list", "public")
  },
  listeners: {
    list: makeQueryReference<{
  "adapter": string | null;
  "state": string | null;
  "limit": number | null;
}, Doc<"listeners">[]>("listeners:list", "public")
  },
  machines: {
    list: makeQueryReference<{
  "state": string | null;
  "provider": string | null;
  "limit": number | null;
}, Doc<"machines">[]>("machines:list", "public"),
    byId: makeQueryReference<{
  "id": Id<"machines">;
}, Doc<"machines"> | null>("machines:byId", "public")
  },
  ports: {
    list: makeQueryReference<{
  "machineId": string | null;
  "serviceId": string | null;
  "state": string | null;
  "limit": number | null;
}, Doc<"ports">[]>("ports:list", "public")
  },
  routes: {
    list: makeQueryReference<{
  "adapter": string | null;
  "limit": number | null;
}, Doc<"routes">[]>("routes:list", "public")
  },
  runs: {
    recent: makeQueryReference<{
  "bundleId": string | null;
  "functionPath": string | null;
  "status": string | null;
  "limit": number | null;
}, Doc<"runs">[]>("runs:recent", "public"),
    byId: makeQueryReference<{
  "id": Id<"runs">;
}, Doc<"runs"> | null>("runs:byId", "public")
  },
  scheduled_jobs: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "status": string | null;
  "limit": number | null;
}, Doc<"scheduled_jobs">[]>("scheduled_jobs:list", "public")
  },
  services: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "machineId": string | null;
  "state": string | null;
  "limit": number | null;
}, Doc<"services">[]>("services:list", "public"),
    byId: makeQueryReference<{
  "id": Id<"services">;
}, Doc<"services"> | null>("services:byId", "public")
  },
  subscriptions: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "adapter": string | null;
  "limit": number | null;
}, Doc<"subscriptions">[]>("subscriptions:list", "public")
  },
  system: {
    status: makeQueryReference<{}, Doc<"system_status"> | null>("system:status", "public")
  },
  tables: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "limit": number | null;
}, Doc<"tables">[]>("tables:list", "public"),
    byName: makeQueryReference<{
  "tenantId": string;
  "name": string;
}, Doc<"tables"> | null>("tables:byName", "public")
  }
};

export const internal = {};
