// Generated by @nimbus/codegen. Do not edit by hand.
import { makeQueryReference } from "convex/browser";
import type { Doc, Id } from "./dataModel";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export const api = {
  adapter_capabilities: {
    list: makeQueryReference<{
  "adapter": string | null;
  "status": string | null;
  "limit": number | null;
}, (JsonValue)[]>("adapter_capabilities:list", "public")
  },
  bundles: {
    list: makeQueryReference<{
  "status": string | null;
  "limit": number | null;
}, (JsonValue)[]>("bundles:list", "public"),
    bySha256: makeQueryReference<{
  "sha256": string;
}, JsonValue>("bundles:bySha256", "public")
  },
  cron_jobs: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "status": string | null;
  "limit": number | null;
}, (JsonValue)[]>("cron_jobs:list", "public")
  },
  events: {
    recent: makeQueryReference<{
  "source": string | null;
  "level": string | null;
  "category": string | null;
  "correlationId": string | null;
  "limit": number | null;
}, (JsonValue)[]>("events:recent", "public")
  },
  functions: {
    list: makeQueryReference<{
  "bundleId": string | null;
  "kind": string | null;
  "limit": number | null;
}, (JsonValue)[]>("functions:list", "public")
  },
  listeners: {
    list: makeQueryReference<{
  "adapter": string | null;
  "state": string | null;
  "limit": number | null;
}, (JsonValue)[]>("listeners:list", "public")
  },
  machines: {
    list: makeQueryReference<{
  "state": string | null;
  "provider": string | null;
  "limit": number | null;
}, (JsonValue)[]>("machines:list", "public"),
    byId: makeQueryReference<{
  "id": Id<"machines">;
}, JsonValue>("machines:byId", "public")
  },
  ports: {
    list: makeQueryReference<{
  "machineId": string | null;
  "serviceId": string | null;
  "state": string | null;
  "limit": number | null;
}, (JsonValue)[]>("ports:list", "public")
  },
  routes: {
    list: makeQueryReference<{
  "adapter": string | null;
  "limit": number | null;
}, (JsonValue)[]>("routes:list", "public")
  },
  runs: {
    recent: makeQueryReference<{
  "bundleId": string | null;
  "functionPath": string | null;
  "status": string | null;
  "limit": number | null;
}, (JsonValue)[]>("runs:recent", "public"),
    byId: makeQueryReference<{
  "id": Id<"runs">;
}, JsonValue>("runs:byId", "public")
  },
  scheduled_jobs: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "status": string | null;
  "limit": number | null;
}, (JsonValue)[]>("scheduled_jobs:list", "public")
  },
  services: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "machineId": string | null;
  "state": string | null;
  "limit": number | null;
}, (JsonValue)[]>("services:list", "public"),
    byId: makeQueryReference<{
  "id": Id<"services">;
}, JsonValue>("services:byId", "public")
  },
  subscriptions: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "adapter": string | null;
  "limit": number | null;
}, (JsonValue)[]>("subscriptions:list", "public")
  },
  system: {
    status: makeQueryReference<{}, JsonValue | null>("system:status", "public")
  },
  tables: {
    list: makeQueryReference<{
  "tenantId": string | null;
  "limit": number | null;
}, (JsonValue)[]>("tables:list", "public"),
    byName: makeQueryReference<{
  "tenantId": string;
  "name": string;
}, JsonValue>("tables:byName", "public")
  }
};

export const internal = {};
