// Generated by @nimbus/codegen. Do not edit by hand.
import type { GenericId } from "convex/values";

export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export type TableNames = "machines" | "services" | "bundles" | "functions" | "source_packages" | "modules" | "tables" | "events" | "runs" | "scheduled_jobs" | "cron_jobs" | "routes" | "listeners" | "subscriptions" | "ports" | "adapter_capabilities" | "system_status";

export type Id<TableName extends string> = GenericId<TableName>;

type DocumentByTable = {
  "machines": {
    _id: Id<"machines">;
    _creationTime: number;
    _updateTime: number;
    "name": string;
    "kind": string;
    "state": string;
    "provider": string;
    "resources": JsonValue | undefined;
    "meta": JsonValue | undefined;
  };
  "services": {
    _id: Id<"services">;
    _creationTime: number;
    _updateTime: number;
    "tenantId": string;
    "name": string;
    "machineId": string | undefined;
    "bundleId": string | undefined;
    "kind": string;
    "state": string;
    "endpoints": (JsonValue)[] | undefined;
    "health": JsonValue | undefined;
  };
  "bundles": {
    _id: Id<"bundles">;
    _creationTime: number;
    _updateTime: number;
    "sha256": string;
    "sizeBytes": number | undefined;
    "sourceRef": string | undefined;
    "status": string;
  };
  "functions": {
    _id: Id<"functions">;
    _creationTime: number;
    _updateTime: number;
    "bundleId": string;
    "path": string;
    "kind": string;
    "argsSchema": JsonValue | undefined;
    "returnsSchema": JsonValue | undefined;
  };
  "source_packages": {
    _id: Id<"source_packages">;
    _creationTime: number;
    _updateTime: number;
    "digest": string;
    "storageKey": string;
    "sizeBytes": number | undefined;
    "unpackedBytes": number | undefined;
    "status": string;
  };
  "modules": {
    _id: Id<"modules">;
    _creationTime: number;
    _updateTime: number;
    "path": string;
    "sourcePackageId": string;
    "sha256": string;
  };
  "tables": {
    _id: Id<"tables">;
    _creationTime: number;
    _updateTime: number;
    "tenantId": string;
    "name": string;
    "schema": JsonValue | undefined;
    "rowCount": number | undefined;
    "lastWriteAt": number | undefined;
  };
  "events": {
    _id: Id<"events">;
    _creationTime: number;
    _updateTime: number;
    "source": string;
    "level": string;
    "category": string;
    "message": string;
    "data": JsonValue | undefined;
    "correlationId": string | undefined;
    "createdAt": number;
  };
  "runs": {
    _id: Id<"runs">;
    _creationTime: number;
    _updateTime: number;
    "bundleId": string | undefined;
    "functionPath": string;
    "kind": string;
    "durationMs": number | undefined;
    "status": string;
    "error": JsonValue | undefined;
    "startedAt": number;
  };
  "scheduled_jobs": {
    _id: Id<"scheduled_jobs">;
    _creationTime: number;
    _updateTime: number;
    "tenantId": string;
    "functionPath": string;
    "scheduledTime": number;
    "status": string;
    "args": JsonValue | undefined;
    "result": JsonValue | undefined;
  };
  "cron_jobs": {
    _id: Id<"cron_jobs">;
    _creationTime: number;
    _updateTime: number;
    "tenantId": string;
    "name": string;
    "schedule": string;
    "functionPath": string;
    "lastRunAt": number | undefined;
    "nextRunAt": number | undefined;
    "status": string;
  };
  "routes": {
    _id: Id<"routes">;
    _creationTime: number;
    _updateTime: number;
    "method": string;
    "path": string;
    "adapter": string;
    "handler": string | undefined;
    "authRequired": boolean;
    "lastRequestAt": number | undefined;
  };
  "listeners": {
    _id: Id<"listeners">;
    _creationTime: number;
    _updateTime: number;
    "listenerId": string;
    "portLeaseId": string | undefined;
    "serviceId": string | undefined;
    "machineId": string | undefined;
    "tenantId": string | undefined;
    "adapter": string;
    "protocol": string;
    "generation": string;
    "leaseEpoch": string | undefined;
    "providerId": string | undefined;
    "actualAddress": string;
    "observedPhase": string;
    "conditions": (JsonValue)[];
    "cleanupState": string;
    "version": string | undefined;
    "error": string | undefined;
  };
  "subscriptions": {
    _id: Id<"subscriptions">;
    _creationTime: number;
    _updateTime: number;
    "tenantId": string | undefined;
    "adapter": string;
    "queryKey": string;
    "clientCount": number;
    "lastDeliveryAt": number | undefined;
    "error": string | undefined;
  };
  "ports": {
    _id: Id<"ports">;
    _creationTime: number;
    _updateTime: number;
    "portLeaseId": string;
    "listenerId": string;
    "machineId": string | undefined;
    "serviceId": string | undefined;
    "tenantId": string | undefined;
    "generation": string;
    "leaseEpoch": string;
    "providerId": string;
    "actualAddress": string;
    "hostPort": number;
    "guestPort": number | undefined;
    "protocol": string;
    "observedPhase": string;
    "conditions": (JsonValue)[];
    "cleanupState": string;
  };
  "adapter_capabilities": {
    _id: Id<"adapter_capabilities">;
    _creationTime: number;
    _updateTime: number;
    "adapter": string;
    "feature": string;
    "status": string;
    "caveat": string | undefined;
    "evidence": string | undefined;
  };
  "system_status": {
    _id: Id<"system_status">;
    _creationTime: number;
    _updateTime: number;
    "name": string;
    "version": string;
    "health": string;
    "startedAt": number;
    "updatedAt": number;
    "details": JsonValue | undefined;
  };
};

type IndexNamesByTable = {
  "machines": "by_name" | "by_state" | "by_provider";
  "services": "by_tenantId" | "by_name" | "by_machineId" | "by_state";
  "bundles": "by_sha256" | "by_status";
  "functions": "by_bundleId" | "by_kind";
  "source_packages": "by_digest" | "by_status";
  "modules": "by_path" | "by_sourcePackageId";
  "tables": "by_tenantId" | "by_name" | "by_tenantId_and_name";
  "events": "by_source" | "by_level" | "by_category" | "by_correlationId" | "by_createdAt";
  "runs": "by_bundleId" | "by_functionPath" | "by_status" | "by_startedAt";
  "scheduled_jobs": "by_tenantId" | "by_status" | "by_scheduledTime";
  "cron_jobs": "by_tenantId" | "by_status" | "by_nextRunAt";
  "routes": "by_adapter" | "by_path";
  "listeners": "by_listenerId" | "by_adapter" | "by_serviceId" | "by_machineId" | "by_observedPhase";
  "subscriptions": "by_tenantId" | "by_adapter";
  "ports": "by_portLeaseId" | "by_listenerId" | "by_machineId" | "by_serviceId" | "by_observedPhase";
  "adapter_capabilities": "by_adapter" | "by_status";
  "system_status": "by_name" | "by_health";
};

export type Doc<TableName extends TableNames> = DocumentByTable[TableName];

export type DataModel = {
  [TableName in TableNames]: {
    document: DocumentByTable[TableName];
    fieldPaths: keyof DocumentByTable[TableName];
    indexes: IndexNamesByTable[TableName];
  };
};
