// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel";

export const scheduledFunctions = {};

export const internalScheduledFunctions = {};
