// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id } from "./dataModel";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export const scheduledFunctions = {};

export const internalScheduledFunctions = {};
