[package]
name = "nimbus-fs"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
fuse = ["dep:fuser"]

[dependencies]
nimbus-blob = { path = "../nimbus-blob" }
nimbus-core = { path = "../nimbus-core" }
nimbus-runtime = { path = "../nimbus-runtime" }
nimbus-storage = { path = "../nimbus-storage" }
async-trait.workspace = true
bytes.workspace = true
cap-std = "4.0.2"
deno_core.workspace = true
deno_fs.workspace = true
deno_io.workspace = true
deno_permissions.workspace = true
fuser = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
proptest = "1"
tempfile.workspace = true
