// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel.js";

export const scheduledFunctions = {
  shareIds: {
    create: makeMutationReference<{}, Id<"shareIds">>("shareIds:create", "public")
  }
};

export const internalScheduledFunctions = {
  digests: {
    store: makeMutationReference<{
  "runtime": "default" | "node";
  "algorithm": string;
  "input": string;
  "output": string;
}, Id<"digests">>("digests:store", "internal")
  }
};
