[package]
name = "nimbus-object-storage"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
nimbus-blob = { path = "../nimbus-blob" }
nimbus-core = { path = "../nimbus-core" }
nimbus-crypto = { path = "../nimbus-crypto" }
nimbus-engine = { path = "../nimbus-engine" }
nimbus-storage = { path = "../nimbus-storage" }
object_store.workspace = true
rand.workspace = true
serde_json.workspace = true
url.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
bytes.workspace = true
tempfile.workspace = true
tokio.workspace = true
