#!/usr/bin/env python3
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
EXTRACT_SCRIPT = REPO_ROOT / "scripts" / "extract-release-notes.sh"

CHANGELOG = """# Changelog

All notable changes to this project will be documented in this file.

## [1.2.3] - 2026-01-02

### Added

- A thing worth reading about.

### Fixed

- A defect that is now gone.

## [1.2.2] - 2026-01-01

### Fixed

- An older defect.

## [1.2.1] - 2025-12-31

<!-- generated by hand -->
"""

EMPTY_SECTION_CHANGELOG = """# Changelog

## [1.2.3] - 2026-01-02


## [1.2.2] - 2026-01-01

### Fixed

- An older defect.
"""


def run(version: str, changelog: Path) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["bash", str(EXTRACT_SCRIPT), version, "--changelog", str(changelog)],
        capture_output=True,
        text=True,
        check=False,
    )


class ExtractReleaseNotesTests(unittest.TestCase):
    def changelog(self, tempdir: str, body: str = CHANGELOG) -> Path:
        path = Path(tempdir) / "CHANGELOG.md"
        path.write_text(body, encoding="utf-8")
        return path

    def test_prints_the_section_for_a_tag(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            result = run("v1.2.3", self.changelog(tempdir))
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(
                result.stdout,
                "### Added\n\n- A thing worth reading about.\n\n"
                "### Fixed\n\n- A defect that is now gone.\n",
            )

    def test_accepts_a_bare_version(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            tagged = run("v1.2.3", self.changelog(tempdir))
            bare = run("1.2.3", self.changelog(tempdir))
            self.assertEqual(bare.returncode, 0, bare.stderr)
            self.assertEqual(bare.stdout, tagged.stdout)

    def test_stops_at_the_next_release_heading(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            result = run("1.2.2", self.changelog(tempdir))
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(result.stdout, "### Fixed\n\n- An older defect.\n")

    def test_reads_the_last_section_to_the_end_of_the_file(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            result = run("1.2.1", self.changelog(tempdir))
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(result.stdout, "<!-- generated by hand -->\n")

    def test_fails_when_the_release_has_no_heading(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            result = run("9.9.9", self.changelog(tempdir))
            self.assertEqual(result.returncode, 1)
            self.assertIn("no", result.stderr)
            self.assertIn("9.9.9", result.stderr)

    def test_fails_when_the_section_is_empty(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            changelog = self.changelog(tempdir, EMPTY_SECTION_CHANGELOG)
            result = run("1.2.3", changelog)
            self.assertEqual(result.returncode, 1)
            self.assertIn("empty section", result.stderr)
            self.assertEqual(result.stdout, "")

    def test_rejects_an_argument_that_is_not_a_version(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            result = run("main", self.changelog(tempdir))
            self.assertEqual(result.returncode, 2)
            self.assertIn("not a release version", result.stderr)


if __name__ == "__main__":
    unittest.main()
