// Generated by @nimbus/codegen. Do not edit by hand.
import { makeMutationReference } from "convex/browser";
import type { Doc, Id, JsonValue } from "./dataModel";

export const scheduledFunctions = {
  messages: {
    send: makeMutationReference<{
  "author": string;
  "body": string;
}, Id<"messages">>("messages:send", "public"),
    scheduleSend: makeMutationReference<{
  "author": string;
  "body": string;
  "delayMs": number;
}, string>("messages:scheduleSend", "public"),
    sendAndSchedule: makeMutationReference<{
  "author": string;
  "body": string;
}, Id<"messages">>("messages:sendAndSchedule", "public")
  }
};

export const internalScheduledFunctions = {
  messages: {
    sendInternal: makeMutationReference<{
  "author": string;
  "body": string;
}, Id<"messages">>("messages:sendInternal", "internal")
  }
};
