// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLlmsTxt from 'starlight-llms-txt';

// Renderer only: content is authored in ../docs (the five public groups).
// DOC1 builds against a placeholder landing; DOC3 wires the content-layer
// glob loaders at ../docs/{get-started,developers,operators,concepts,reference}.
// Theme tokens map DESIGN.md's product palette onto Starlight — see
// src/styles/custom.css and DESIGN.md §Documentation site.
export default defineConfig({
  site: 'https://nimbusdocs.com',
  integrations: [
    starlight({
      title: 'Nimbus',
      description:
        'The single-binary backend for apps and AI agents. Drop-in compatible with Convex, Firestore, MongoDB, and DynamoDB.',
      favicon: '/favicon.svg',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/nimbus/nimbus',
        },
      ],
      customCss: [
        '@fontsource-variable/jetbrains-mono',
        './src/styles/custom.css',
      ],
      // Nested groups are explicit: Starlight's autogenerated group labels
      // are raw directory names, so each adapter directory gets a label here.
      // A new docs/ subdirectory must be added to this list to appear.
      sidebar: [
        { label: 'Get started', items: [{ autogenerate: { directory: 'get-started' } }] },
        {
          label: 'Developers',
          items: [
            'developers',
            'developers/first-app',
            'developers/auth',
            { label: 'Convex', items: [{ autogenerate: { directory: 'developers/convex' } }] },
            { label: 'Firestore', items: [{ autogenerate: { directory: 'developers/firebase' } }] },
            { label: 'Cloud Functions', items: [{ autogenerate: { directory: 'developers/cloud-functions' } }] },
            { label: 'MongoDB', items: [{ autogenerate: { directory: 'developers/mongodb' } }] },
            { label: 'DynamoDB', items: [{ autogenerate: { directory: 'developers/dynamodb' } }] },
            { label: 'Native API', items: [{ autogenerate: { directory: 'developers/native' } }] },
            { label: 'Node.js runtime', items: [{ autogenerate: { directory: 'developers/runtimes/nodejs' } }] },
            { label: 'SDK', items: [{ autogenerate: { directory: 'developers/sdk' } }] },
          ],
        },
        { label: 'Operators', items: [{ autogenerate: { directory: 'operators' } }] },
        {
          label: 'Concepts',
          items: [
            'concepts',
            'concepts/how-nimbus-works',
            'concepts/tenant-isolation',
            'concepts/data-and-mutations',
            'concepts/adapter-boundary',
            'concepts/runtime-permissions',
            'concepts/resource-model',
            'concepts/scaling',
            'concepts/nodejs-runtime',
            { label: 'Architecture', items: [{ autogenerate: { directory: 'concepts/architecture' } }] },
          ],
        },
        {
          label: 'Reference',
          items: [
            'reference',
            'reference/cli',
            'reference/configuration',
            'reference/deploy-admin-api',
            'reference/current-capabilities',
            { label: 'SDK', items: [{ autogenerate: { directory: 'reference/sdk' } }] },
            { label: 'Convex', items: [{ autogenerate: { directory: 'reference/convex' } }] },
            { label: 'Firestore', items: [{ autogenerate: { directory: 'reference/firebase' } }] },
            { label: 'Cloud Functions', items: [{ autogenerate: { directory: 'reference/cloud-functions' } }] },
            { label: 'MongoDB', items: [{ autogenerate: { directory: 'reference/mongodb' } }] },
            { label: 'DynamoDB', items: [{ autogenerate: { directory: 'reference/dynamodb' } }] },
            { label: 'Native API', items: [{ autogenerate: { directory: 'reference/native' } }] },
            { label: 'Node.js runtime', items: [{ autogenerate: { directory: 'reference/runtimes' } }] },
          ],
        },
      ],
      plugins: [
        starlightLlmsTxt({
          projectName: 'Nimbus',
          // llms-small.txt keeps the task corpus (get started, developers,
          // operators, core concepts, CLI/config/SDK reference) and drops the
          // deep architecture pages and per-protocol compatibility matrices,
          // which stay in llms-full.txt.
          exclude: [
            'concepts/architecture/**',
            'reference/convex/**',
            'reference/firebase/**',
            'reference/cloud-functions/**',
            'reference/mongodb/**',
            'reference/dynamodb/**',
            'reference/native/**',
            'reference/runtimes/**',
          ],
        }),
      ],
    }),
  ],
});
