// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightLlmsTxt from 'starlight-llms-txt';

// Renderer only: content is authored in ../docs (the five public groups).
// DOC1 builds against a placeholder landing; DOC3 wires the content-layer
// glob loaders at ../docs/{get-started,developers,operators,concepts,reference}.
// Theme tokens map DESIGN.md's product palette onto Starlight — see
// src/styles/custom.css and DESIGN.md §Documentation site.
export default defineConfig({
  site: 'https://nimbusdocs.com',
  integrations: [
    starlight({
      // The wordmark is lowercase "nimbus" next to the cloud mark
      // (DESIGN.md §Brand Palette). Transparent logo variants so the mark
      // sits on the nav's own background in both modes.
      title: 'nimbus',
      logo: {
        light: '../docs/brand/logo/nimbus-warm-transparent.svg',
        dark: '../docs/brand/logo/nimbus-night-blue-transparent.svg',
      },
      description:
        'The single-binary backend for apps and AI agents. Drop-in compatible with Convex, Firestore, MongoDB, and DynamoDB.',
      favicon: '/favicon.svg',
      head: [
        // The favicon must follow the page's resolved theme, not the OS:
        // an SVG prefers-color-scheme query only sees the OS scheme, so a
        // light page on a dark OS would show the night favicon. Starlight
        // resolves data-theme in a blocking head script before this runs;
        // /favicon.svg (media-query auto) stays as the no-JS fallback.
        {
          tag: 'script',
          content: `(function () {
  var init = function () {
    var link = document.querySelector('link[rel*="icon"]');
    if (!link) return;
    var update = function () {
      link.href =
        document.documentElement.dataset.theme === 'dark'
          ? '/favicon-night.svg'
          : '/favicon-warm.svg';
    };
    update();
    new MutationObserver(update).observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['data-theme'],
    });
  };
  // Head order is not guaranteed: this script can precede the favicon
  // <link> in the parsed head, so wait for the DOM when it does.
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();`,
        },
      ],
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/nimbus/nimbus',
        },
      ],
      customCss: [
        '@fontsource-variable/jetbrains-mono',
        './src/styles/custom.css',
      ],
      // Nested groups are explicit: Starlight's autogenerated group labels
      // are raw directory names, so each adapter directory gets a label here.
      // A new docs/ subdirectory must be added to this list to appear.
      sidebar: [
        { label: 'Get started', items: [{ autogenerate: { directory: 'get-started' } }] },
        {
          label: 'Developers',
          items: [
            'developers',
            'developers/first-app',
            'developers/auth',
            // Every protocol surface lives under one "Adapters" category; each
            // adapter is collapsed so the growing list stays scannable.
            {
              label: 'Adapters',
              items: [
                { label: 'Convex', collapsed: true, items: [{ autogenerate: { directory: 'developers/convex' } }] },
                { label: 'Firestore', collapsed: true, items: [{ autogenerate: { directory: 'developers/firebase' } }] },
                { label: 'Cloud Functions', collapsed: true, items: [{ autogenerate: { directory: 'developers/cloud-functions' } }] },
                { label: 'MongoDB', collapsed: true, items: [{ autogenerate: { directory: 'developers/mongodb' } }] },
                { label: 'DynamoDB', collapsed: true, items: [{ autogenerate: { directory: 'developers/dynamodb' } }] },
                { label: 'Native API', collapsed: true, items: [{ autogenerate: { directory: 'developers/native' } }] },
              ],
            },
            { label: 'Node.js runtime', items: [{ autogenerate: { directory: 'developers/runtimes/nodejs' } }] },
          ],
        },
        { label: 'Agents', items: [{ autogenerate: { directory: 'agents' } }] },
        { label: 'Operators', items: [{ autogenerate: { directory: 'operators' } }] },
        {
          label: 'Concepts',
          // Pedagogical order — primitives before composites: engine, then
          // data, then isolation, then the surfaces and runtimes built on
          // them, then the resource model, then how it all scales.
          items: [
            'concepts',
            'concepts/how-nimbus-works',
            'concepts/data-and-mutations',
            'concepts/tenant-isolation',
            'concepts/adapter-boundary',
            'concepts/runtime-permissions',
            'concepts/nodejs-runtime',
            'concepts/resource-model',
            'concepts/scaling',
            { label: 'Architecture', items: [{ autogenerate: { directory: 'concepts/architecture' } }] },
          ],
        },
        {
          label: 'Reference',
          items: [
            'reference',
            'reference/cli',
            'reference/configuration',
            'reference/deploy-admin-api',
            'reference/current-capabilities',
            { label: 'SDK', items: [{ autogenerate: { directory: 'reference/sdk' } }] },
            // Every protocol surface lives under one "Adapters" category, led by
            // the cross-adapter matrix; each adapter is collapsed for scannability.
            {
              label: 'Adapters',
              items: [
                'reference/adapter-capabilities',
                { label: 'Convex', collapsed: true, items: [{ autogenerate: { directory: 'reference/convex' } }] },
                { label: 'Firestore', collapsed: true, items: [{ autogenerate: { directory: 'reference/firebase' } }] },
                { label: 'Cloud Functions', collapsed: true, items: [{ autogenerate: { directory: 'reference/cloud-functions' } }] },
                { label: 'MongoDB', collapsed: true, items: [{ autogenerate: { directory: 'reference/mongodb' } }] },
                { label: 'DynamoDB', collapsed: true, items: [{ autogenerate: { directory: 'reference/dynamodb' } }] },
                { label: 'S3', collapsed: true, items: [{ autogenerate: { directory: 'reference/s3' } }] },
                { label: 'Cloudflare', collapsed: true, items: [{ autogenerate: { directory: 'reference/cloudflare' } }] },
                { label: 'KV (Redis)', collapsed: true, items: [{ autogenerate: { directory: 'reference/kv' } }] },
                { label: 'Native API', collapsed: true, items: [{ autogenerate: { directory: 'reference/native' } }] },
              ],
            },
            { label: 'Node.js runtime', items: [{ autogenerate: { directory: 'reference/runtimes' } }] },
          ],
        },
      ],
      plugins: [
        starlightLlmsTxt({
          projectName: 'Nimbus',
          // llms-small.txt keeps the task corpus (get started, developers,
          // operators, core concepts, CLI/config/SDK reference) and drops the
          // deep architecture pages and per-protocol compatibility matrices,
          // which stay in llms-full.txt.
          exclude: [
            'concepts/architecture/**',
            'reference/convex/**',
            'reference/firebase/**',
            'reference/cloud-functions/**',
            'reference/mongodb/**',
            'reference/dynamodb/**',
            'reference/s3/**',
            'reference/cloudflare/**',
            'reference/kv/**',
            'reference/native/**',
            'reference/runtimes/**',
          ],
        }),
      ],
    }),
  ],
});
