[package]
name = "nimbus-kv"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
hex.workspace = true
nimbus-core = { path = "../nimbus-core" }
nimbus-network = { path = "../nimbus-network" }
nimbus-storage = { path = "../nimbus-storage" }
rand.workspace = true
redis-protocol.workspace = true
subtle.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ulid.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
nimbus-testing = { path = "../nimbus-testing" }
redis.workspace = true
tempfile.workspace = true
