// Generated by @neovex/codegen. Do not edit by hand.
import { makeMutationReference, makePaginatedQueryReference, makeQueryReference } from "convex/browser";
import type { Doc, Id } from "./dataModel";

type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

export const api = {
  messages: {
    list: makeQueryReference<{}, Doc<"messages">[]>("messages:list", "public"),
    byAuthor: makeQueryReference<{
  "author": string;
}, Doc<"messages">[]>("messages:byAuthor", "public"),
    maybeByAuthor: makeQueryReference<{
  "author": string | null;
}, ({
  "_id": Id<"messages">;
  "_creationTime": number;
  "_updateTime": number;
  "author": string;
  "body": string;
})[]>("messages:maybeByAuthor", "public"),
    latestByAuthor: makeQueryReference<{
  "author": string;
}, Doc<"messages"> | null>("messages:latestByAuthor", "public"),
    uniqueByAuthor: makeQueryReference<{
  "author": string;
}, Doc<"messages"> | null>("messages:uniqueByAuthor", "public"),
    byId: makeQueryReference<{
  "id": Id<"messages">;
}, Doc<"messages"> | null>("messages:byId", "public"),
    listPage: makePaginatedQueryReference<{
  "author": string | null;
}, {
  "_id": Id<"messages">;
  "_creationTime": number;
  "_updateTime": number;
  "author": string;
  "body": string;
}>("messages:listPage", "public"),
    send: makeMutationReference<{
  "author": string;
  "body": string;
}, string>("messages:send", "public"),
    scheduleSend: makeMutationReference<{
  "author": string;
  "body": string;
  "delayMs": number;
}, string>("messages:scheduleSend", "public"),
    rename: makeMutationReference<{
  "id": Id<"messages">;
  "body": string;
}, string>("messages:rename", "public"),
    remove: makeMutationReference<{
  "id": Id<"messages">;
}, null>("messages:remove", "public")
  }
};

export const internal = {
  messages: {
    sendInternal: makeMutationReference<{
  "author": string;
  "body": string;
}, Id<"messages">>("messages:sendInternal", "internal")
  }
};
